// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-10-08
//     C# generater version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unoffical sample for the Youtubeanalytics v1 API for C#. 
// This sample is designed to be used with the Google .Net client library. (https://github.com/google/google-api-dotnet-client)
// 
// API Description: Retrieves your YouTube Analytics data.
// API Documentation Link http://developers.google.com/youtube/analytics/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/Youtubeanalytics/v1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// This sample code uses the Google .Net client library (https://github.com/google/google-api-dotnet-client)
//
// NuGet package:
//
// Location: https://www.nuget.org/packages/Google.Apis.Youtubeanalytics.v1/ 
// Install Command: PM>  Install-Package Google.Apis.Youtubeanalytics.v1
//
//------------------------------------------------------------------------------  
using Google.Apis.Youtubeanalytics.v1;
using Google.Apis.Youtubeanalytics.v1.Data;
using System;

namespace GoogleSamplecSharpSample.Youtubeanalyticsv1.Methods
{
  
    public static class ReportsSample
    {

        public class ReportsQueryOptionalParms
        {
            /// The currency to which financial metrics should be converted. The default is US Dollar (USD). If the result contains no financial metrics, this flag will be ignored. Responds with an error if the specified currency is not recognized.
            public string Currency { get; set; }  
            /// A comma-separated list of YouTube Analytics dimensions, such as views or ageGroup,gender. See the Available Reports document for a list of the reports that you can retrieve and the dimensions used for those reports. Also see the Dimensions document for definitions of those dimensions.
            public string Dimensions { get; set; }  
            /// A list of filters that should be applied when retrieving YouTube Analytics data. The Available Reports document identifies the dimensions that can be used to filter each report, and the Dimensions document defines those dimensions. If a request uses multiple filters, join them together with a semicolon (;), and the returned result table will satisfy both filters. For example, a filters parameter value of video==dMH0bHeiRNg;country==IT restricts the result set to include data for the given video in Italy.
            public string Filters { get; set; }  
            /// If set to true historical data (i.e. channel data from before the linking of the channel to the content owner) will be retrieved.
            public bool? Include-historical-channel-data { get; set; }  
            /// The maximum number of rows to include in the response.
            public int? Max-results { get; set; }  
            /// A comma-separated list of dimensions or metrics that determine the sort order for YouTube Analytics data. By default the sort order is ascending. The '-' prefix causes descending sort order.
            public string Sort { get; set; }  
            /// An index of the first entity to retrieve. Use this parameter as a pagination mechanism along with the max-results parameter (one-based, inclusive).
            public int? Start-index { get; set; }  
        
        }
 
        /// <summary>
        /// Retrieve your YouTube Analytics reports. 
        /// Documentation https://developers.google.com/youtubeanalytics/v1/reference/reports/query
        /// Generation Note: This does not always build corectly.  Google needs to standardise things I need to figuer out which ones are wrong.
        /// </summary>
        /// <param name="service">Authenticated Youtubeanalytics service.</param>  
        /// <param name="ids">Identifies the YouTube channel or content owner for which you are retrieving YouTube Analytics data.- To request data for a YouTube user, set the ids parameter value to channel==CHANNEL_ID, where CHANNEL_ID specifies the unique YouTube channel ID.- To request data for a YouTube CMS content owner, set the ids parameter value to contentOwner==OWNER_NAME, where OWNER_NAME is the CMS name of the content owner.</param>
        /// <param name="start-date">The start date for fetching YouTube Analytics data. The value should be in YYYY-MM-DD format.</param>
        /// <param name="end-date">The end date for fetching YouTube Analytics data. The value should be in YYYY-MM-DD format.</param>
        /// <param name="metrics">A comma-separated list of YouTube Analytics metrics, such as views or likes,dislikes. See the Available Reports document for a list of the reports that you can retrieve and the metrics available in each report, and see the Metrics document for definitions of those metrics.</param>
        /// <param name="optional">Optional paramaters.</param>
        /// <returns>ResultTableResponse</returns>
        public static ResultTable Query(YoutubeanalyticsService service, string ids, string start-date, string end-date, string metrics, ReportsQueryOptionalParms optional = null)
        {
            try
            {
                // Initial validation.
                if (service == null)
                    throw new ArgumentNullException("service");
                if (ids == null)
                    throw new ArgumentNullException(ids);
                if (start-date == null)
                    throw new ArgumentNullException(start-date);
                if (end-date == null)
                    throw new ArgumentNullException(end-date);
                if (metrics == null)
                    throw new ArgumentNullException(metrics);

                // Building the initial request.
                var request = service.Reports.Query(ids, start-date, end-date, metrics);

                // Applying optional parameters to the request.                
                request = (ReportsResource.QueryRequest)SampleHelpers.ApplyOptionalParms(request, optional);

                // Requesting data.
                return request.Execute();
            }
            catch (Exception ex)
            {
                throw new Exception("Request Reports.Query failed.", ex);
            }
        }
        
        }

        public static class SampleHelpers
        {

        /// <summary>
        /// Using reflection to apply optional parameters to the request.  
        /// 
        /// If the optonal parameters are null then we will just return the request as is.
        /// </summary>
        /// <param name="request">The request. </param>
        /// <param name="optional">The optional parameters. </param>
        /// <returns></returns>
        public static object ApplyOptionalParms(object request, object optional)
        {
            if (optional == null)
                return request;

            System.Reflection.PropertyInfo[] optionalProperties = (optional.GetType()).GetProperties();

            foreach (System.Reflection.PropertyInfo property in optionalProperties)
            {
                // Copy value from optional parms to the request.  They should have the same names and datatypes.
                System.Reflection.PropertyInfo piShared = (request.GetType()).GetProperty(property.Name);
				if (property.GetValue(optional, null) != null) // TODO Test that we do not add values for items that are null
					piShared.SetValue(request, property.GetValue(optional, null), null);
            }

            return request;
        }
    }
}