 


// Copyright 2015 DAIMTO :  www.daimto.com
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Build date: 11/17/2015 13:52:58
//     C# generater version: 1.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Google.Apis.Analytics.v3;
using Google.Apis.Analytics.v3.Data;

namespace DAIMTO.Analytics.v3.Sample
{
    class ManagementCustomMetricsSample
    {
			 /// <summary>
		/// Get a custom metric to which the user has access.
		/// Documentation: https://developers.google.com/analytics//v3/custommetrics/get
		/// </summary>
		/// <param name="service">Valid authentcated AnalyticsService</param>
		/// <param name="accountId">Account ID for the custom metric to retrieve.</param>
       /// <param name="webPropertyId">Web property ID for the custom metric to retrieve.</param>
       /// <param name="customMetricId">The ID of the custom metric to retrieve.</param>
        /// <returns></returns>
		 public static CustomMetric get(AnalyticsService service, string accountId, string webPropertyId, string customMetricId)
		 {
		  try
            {
                var request = service.Management.CustomMetrics.Get(accountId, webPropertyId, customMetricId);
		  return  request.Execute();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Request Failed " + ex.Message);
                throw ex;
            }
		 
		 
		 }
		 
		
		 /// <summary>
		/// Create a new custom metric.
		/// Documentation: https://developers.google.com/analytics//v3/custommetrics/insert
		/// </summary>
		/// <param name="service">Valid authentcated AnalyticsService</param>
		/// <param name="body">Valid CustomMetric Body</param>
       /// <param name="accountId">Account ID for the custom metric to create.</param>
       /// <param name="webPropertyId">Web property ID for the custom dimension to create.</param>
        /// <returns></returns>
		 public static CustomMetric insert(AnalyticsService service, CustomMetric body, string accountId, string webPropertyId)
		 {
		  try
            {
                var request = service.Management.CustomMetrics.Insert(body, accountId, webPropertyId);
		  return  request.Execute();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Request Failed " + ex.Message);
                throw ex;
            }
		 
		 
		 }
		 
		
		 /// <summary>
		/// Lists custom metrics to which the user has access.
		/// Documentation: https://developers.google.com/analytics//v3/custommetrics/list
		/// </summary>
		/// <param name="service">Valid authentcated AnalyticsService</param>
		/// <param name="accountId">Account ID for the custom metrics to retrieve.</param>
       /// <param name="webPropertyId">Web property ID for the custom metrics to retrieve.</param>
        /// <returns></returns>
		 public static CustomMetrics list(AnalyticsService service, string accountId, string webPropertyId)
		 {
		  try
            {
                var request = service.Management.CustomMetrics.List(accountId, webPropertyId);
		  return  request.Execute();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Request Failed " + ex.Message);
                throw ex;
            }
		 
		 
		 }
		 
		
		 /// <summary>
		/// Updates an existing custom metric. This method supports patch semantics.
		/// Documentation: https://developers.google.com/analytics//v3/custommetrics/patch
		/// </summary>
		/// <param name="service">Valid authentcated AnalyticsService</param>
		/// <param name="body">Valid CustomMetric Body</param>
       /// <param name="accountId">Account ID for the custom metric to update.</param>
       /// <param name="webPropertyId">Web property ID for the custom metric to update.</param>
       /// <param name="customMetricId">Custom metric ID for the custom metric to update.</param>
        /// <returns></returns>
		 public static CustomMetric patch(AnalyticsService service, CustomMetric body, string accountId, string webPropertyId, string customMetricId)
		 {
		  try
            {
                var request = service.Management.CustomMetrics.Patch(body, accountId, webPropertyId, customMetricId);
		  return  request.Execute();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Request Failed " + ex.Message);
                throw ex;
            }
		 
		 
		 }
		 
		
		 /// <summary>
		/// Updates an existing custom metric.
		/// Documentation: https://developers.google.com/analytics//v3/custommetrics/update
		/// </summary>
		/// <param name="service">Valid authentcated AnalyticsService</param>
		/// <param name="body">Valid CustomMetric Body</param>
       /// <param name="accountId">Account ID for the custom metric to update.</param>
       /// <param name="webPropertyId">Web property ID for the custom metric to update.</param>
       /// <param name="customMetricId">Custom metric ID for the custom metric to update.</param>
        /// <returns></returns>
		 public static CustomMetric update(AnalyticsService service, CustomMetric body, string accountId, string webPropertyId, string customMetricId)
		 {
		  try
            {
                var request = service.Management.CustomMetrics.Update(body, accountId, webPropertyId, customMetricId);
		  return  request.Execute();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Request Failed " + ex.Message);
                throw ex;
            }
		 
		 
		 }
		 
		
    }


}

