{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/adexchange.seller": {
     "description": "View and manage your Ad Exchange data"
    },
    "https://www.googleapis.com/auth/adexchange.seller.readonly": {
     "description": "View your Ad Exchange data"
    }
   }
  }
 },
 "basePath": "/adexchangeseller/v1/",
 "baseUrl": "https://www.googleapis.com/adexchangeseller/v1/",
 "batchPath": "batch/adexchangeseller/v1",
 "canonicalName": "Ad Exchange Seller",
 "description": "Accesses the inventory of Ad Exchange seller users and generates reports.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/ad-exchange/seller-rest/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/EberIAMM9RntL16aqUh0FmyQxWY\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "adexchangeseller:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "adexchangeseller",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "adclients": {
   "methods": {
    "list": {
     "description": "List all ad clients in this Ad Exchange account.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "adexchangeseller.adclients.list",
     "path": "adclients",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "adunits": {
   "methods": {
    "get": {
     "description": "Gets the specified ad unit in the specified ad client.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "adexchangeseller.adunits.get",
     "path": "adclients/{adClientId}/adunits/{adUnitId}",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List all ad units in the specified ad client for this Ad Exchange account.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "adexchangeseller.adunits.list",
     "path": "adclients/{adClientId}/adunits",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "customchannels": {
     "methods": {
      "list": {
       "description": "List all custom channels which the specified ad unit belongs to.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "adexchangeseller.adunits.customchannels.list",
       "path": "adclients/{adClientId}/adunits/{adUnitId}/customchannels",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "customchannels": {
   "methods": {
    "get": {
     "description": "Get the specified custom channel from the specified ad client.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "adexchangeseller.customchannels.get",
     "path": "adclients/{adClientId}/customchannels/{customChannelId}",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List all custom channels in the specified ad client for this Ad Exchange account.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "adexchangeseller.customchannels.list",
     "path": "adclients/{adClientId}/customchannels",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "adunits": {
     "methods": {
      "list": {
       "description": "List all ad units in the specified custom channel.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "adexchangeseller.customchannels.adunits.list",
       "path": "adclients/{adClientId}/customchannels/{customChannelId}/adunits",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "reports": {
   "methods": {
    "generate": {
     "description": "Generate an Ad Exchange report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify \"alt=csv\" as a query parameter.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "adexchangeseller.reports.generate",
     "path": "reports",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ],
     "supportsMediaDownload": true,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "saved": {
     "methods": {
      "generate": {
       "description": "Generate an Ad Exchange report based on the saved report ID sent in the query parameters.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "adexchangeseller.reports.saved.generate",
       "path": "reports/{savedReportId}",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "List all saved reports in this Ad Exchange account.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "adexchangeseller.reports.saved.list",
       "path": "reports/saved",
       "scopes": [
        "https://www.googleapis.com/auth/adexchange.seller",
        "https://www.googleapis.com/auth/adexchange.seller.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "urlchannels": {
   "methods": {
    "list": {
     "description": "List all URL channels in the specified ad client for this Ad Exchange account.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "adexchangeseller.urlchannels.list",
     "path": "adclients/{adClientId}/urlchannels",
     "scopes": [
      "https://www.googleapis.com/auth/adexchange.seller",
      "https://www.googleapis.com/auth/adexchange.seller.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20160805",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "adexchangeseller/v1/",
 "title": "Ad Exchange Seller API",
 "version": "v1",
 "version_module": null
}