{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/admin.directory.customer": {
     "description": "View and manage customer related information"
    },
    "https://www.googleapis.com/auth/admin.directory.customer.readonly": {
     "description": "View customer related information"
    },
    "https://www.googleapis.com/auth/admin.directory.device.chromeos": {
     "description": "View and manage your Chrome OS devices' metadata"
    },
    "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly": {
     "description": "View your Chrome OS devices' metadata"
    },
    "https://www.googleapis.com/auth/admin.directory.device.mobile": {
     "description": "View and manage your mobile devices' metadata"
    },
    "https://www.googleapis.com/auth/admin.directory.device.mobile.action": {
     "description": "Manage your mobile devices by performing administrative tasks"
    },
    "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly": {
     "description": "View your mobile devices' metadata"
    },
    "https://www.googleapis.com/auth/admin.directory.domain": {
     "description": "View and manage the provisioning of domains for your customers"
    },
    "https://www.googleapis.com/auth/admin.directory.domain.readonly": {
     "description": "View domains related to your customers"
    },
    "https://www.googleapis.com/auth/admin.directory.group": {
     "description": "View and manage the provisioning of groups on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.group.member": {
     "description": "View and manage group subscriptions on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.group.member.readonly": {
     "description": "View group subscriptions on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.group.readonly": {
     "description": "View groups on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.notifications": {
     "description": "View and manage notifications received on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.orgunit": {
     "description": "View and manage organization units on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.orgunit.readonly": {
     "description": "View organization units on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.resource.calendar": {
     "description": "View and manage the provisioning of calendar resources on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly": {
     "description": "View calendar resources on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.rolemanagement": {
     "description": "Manage delegated admin roles for your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly": {
     "description": "View delegated admin roles for your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user": {
     "description": "View and manage the provisioning of users on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user.alias": {
     "description": "View and manage user aliases on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user.alias.readonly": {
     "description": "View user aliases on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user.readonly": {
     "description": "View users on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.user.security": {
     "description": "Manage data access permissions for users on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.userschema": {
     "description": "View and manage the provisioning of user schemas on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.userschema.readonly": {
     "description": "View user schemas on your domain"
    }
   }
  }
 },
 "basePath": "/admin/directory/v1/",
 "baseUrl": "https://www.googleapis.com/admin/directory/v1/",
 "batchPath": "batch/admin/directory_v1",
 "canonicalName": "directory",
 "description": "The Admin SDK Directory API lets you view and manage enterprise resources such as users and groups, administrative notifications, security features, and more.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/admin-sdk/directory/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/JB19efQGH5f-JRT49yZz7BTyNQU\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "admin:directory_v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "admin",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": "admin",
 "protocol": "rest",
 "resources": {
  "asps": {
   "methods": {
    "delete": {
     "description": "Delete an ASP issued by a user.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.asps.delete",
     "path": "users/{userKey}/asps/{codeId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Get information about an ASP issued by a user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.asps.get",
     "path": "users/{userKey}/asps/{codeId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List the ASPs issued by a user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.asps.list",
     "path": "users/{userKey}/asps",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "channels": {
   "methods": {
    "stop": {
     "description": "Stop watching resources through this channel",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "admin.channels.stop",
     "path": "/admin/directory_v1/channels/stop",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/admin.directory.user.alias",
      "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
      "https://www.googleapis.com/auth/admin.directory.user.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "chromeosdevices": {
   "methods": {
    "action": {
     "description": "Take action on Chrome OS Device",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.chromeosdevices.action",
     "path": "customer/{customerId}/devices/chromeos/{resourceId}/action",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieve Chrome OS Device",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.chromeosdevices.get",
     "path": "customer/{customerId}/devices/chromeos/{deviceId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos",
      "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieve all Chrome OS Devices of a customer (paginated)",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.chromeosdevices.list",
     "path": "customer/{customerId}/devices/chromeos",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos",
      "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "moveDevicesToOu": {
     "description": "Move or insert multiple Chrome OS Devices to Organization Unit",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.chromeosdevices.moveDevicesToOu",
     "path": "customer/{customerId}/devices/chromeos/moveDevicesToOu",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Update Chrome OS Device. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.chromeosdevices.patch",
     "path": "customer/{customerId}/devices/chromeos/{deviceId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update Chrome OS Device",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.chromeosdevices.update",
     "path": "customer/{customerId}/devices/chromeos/{deviceId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.chromeos"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "customers": {
   "methods": {
    "get": {
     "description": "Retrieves a customer.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.customers.get",
     "path": "customers/{customerKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.customer",
      "https://www.googleapis.com/auth/admin.directory.customer.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates a customer. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.customers.patch",
     "path": "customers/{customerKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.customer"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a customer.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.customers.update",
     "path": "customers/{customerKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.customer"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "domainAliases": {
   "methods": {
    "delete": {
     "description": "Deletes a Domain Alias of the customer.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.domainAliases.delete",
     "path": "customer/{customer}/domainaliases/{domainAliasName}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.domain"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieves a domain alias of the customer.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.domainAliases.get",
     "path": "customer/{customer}/domainaliases/{domainAliasName}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.domain",
      "https://www.googleapis.com/auth/admin.directory.domain.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a Domain alias of the customer.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.domainAliases.insert",
     "path": "customer/{customer}/domainaliases",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.domain"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists the domain aliases of the customer.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.domainAliases.list",
     "path": "customer/{customer}/domainaliases",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.domain",
      "https://www.googleapis.com/auth/admin.directory.domain.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "domains": {
   "methods": {
    "delete": {
     "description": "Deletes a domain of the customer.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.domains.delete",
     "path": "customer/{customer}/domains/{domainName}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.domain"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieves a domain of the customer.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.domains.get",
     "path": "customer/{customer}/domains/{domainName}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.domain",
      "https://www.googleapis.com/auth/admin.directory.domain.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a domain of the customer.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.domains.insert",
     "path": "customer/{customer}/domains",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.domain"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists the domains of the customer.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.domains.list",
     "path": "customer/{customer}/domains",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.domain",
      "https://www.googleapis.com/auth/admin.directory.domain.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "groups": {
   "methods": {
    "delete": {
     "description": "Delete Group",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.groups.delete",
     "path": "groups/{groupKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieve Group",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.groups.get",
     "path": "groups/{groupKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Create Group",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.groups.insert",
     "path": "groups",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieve all groups in a domain (paginated)",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.groups.list",
     "path": "groups",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Update Group. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.groups.patch",
     "path": "groups/{groupKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update Group",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.groups.update",
     "path": "groups/{groupKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "aliases": {
     "methods": {
      "delete": {
       "description": "Remove a alias for the group",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "directory.groups.aliases.delete",
       "path": "groups/{groupKey}/aliases/{alias}",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.group"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Add a alias for the group",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "directory.groups.aliases.insert",
       "path": "groups/{groupKey}/aliases",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.group"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "List all aliases for a group",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "directory.groups.aliases.list",
       "path": "groups/{groupKey}/aliases",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.group",
        "https://www.googleapis.com/auth/admin.directory.group.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": true,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "members": {
   "methods": {
    "delete": {
     "description": "Remove membership.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.members.delete",
     "path": "groups/{groupKey}/members/{memberKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieve Group Member",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.members.get",
     "path": "groups/{groupKey}/members/{memberKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member",
      "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
      "https://www.googleapis.com/auth/admin.directory.group.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Add user to the specified group.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.members.insert",
     "path": "groups/{groupKey}/members",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieve all members in a group (paginated)",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.members.list",
     "path": "groups/{groupKey}/members",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member",
      "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
      "https://www.googleapis.com/auth/admin.directory.group.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Update membership of a user in the specified group. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.members.patch",
     "path": "groups/{groupKey}/members/{memberKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update membership of a user in the specified group.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.members.update",
     "path": "groups/{groupKey}/members/{memberKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.group.member"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "mobiledevices": {
   "methods": {
    "action": {
     "description": "Take action on Mobile Device",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.mobiledevices.action",
     "path": "customer/{customerId}/devices/mobile/{resourceId}/action",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.mobile",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.action"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Delete Mobile Device",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.mobiledevices.delete",
     "path": "customer/{customerId}/devices/mobile/{resourceId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.mobile"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieve Mobile Device",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.mobiledevices.get",
     "path": "customer/{customerId}/devices/mobile/{resourceId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.mobile",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieve all Mobile Devices of a customer (paginated)",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.mobiledevices.list",
     "path": "customer/{customerId}/devices/mobile",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.device.mobile",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
      "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "notifications": {
   "methods": {
    "delete": {
     "description": "Deletes a notification",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.notifications.delete",
     "path": "customer/{customer}/notifications/{notificationId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieves a notification.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.notifications.get",
     "path": "customer/{customer}/notifications/{notificationId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of notifications.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.notifications.list",
     "path": "customer/{customer}/notifications",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates a notification. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.notifications.patch",
     "path": "customer/{customer}/notifications/{notificationId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a notification.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.notifications.update",
     "path": "customer/{customer}/notifications/{notificationId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.notifications"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "orgunits": {
   "methods": {
    "delete": {
     "description": "Remove Organization Unit",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.orgunits.delete",
     "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieve Organization Unit",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.orgunits.get",
     "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit",
      "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Add Organization Unit",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.orgunits.insert",
     "path": "customer/{customerId}/orgunits",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieve all Organization Units",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.orgunits.list",
     "path": "customer/{customerId}/orgunits",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit",
      "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Update Organization Unit. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.orgunits.patch",
     "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update Organization Unit",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.orgunits.update",
     "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.orgunit"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "privileges": {
   "methods": {
    "list": {
     "description": "Retrieves a paginated list of all privileges for a customer.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.privileges.list",
     "path": "customer/{customer}/roles/ALL/privileges",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement",
      "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "resources": {
   "methods": null,
   "resources": {
    "calendars": {
     "methods": {
      "delete": {
       "description": "Deletes a calendar resource.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "directory.resources.calendars.delete",
       "path": "customer/{customer}/resources/calendars/{calendarResourceId}",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.resource.calendar"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Retrieves a calendar resource.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "directory.resources.calendars.get",
       "path": "customer/{customer}/resources/calendars/{calendarResourceId}",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.resource.calendar",
        "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Inserts a calendar resource.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "directory.resources.calendars.insert",
       "path": "customer/{customer}/resources/calendars",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.resource.calendar"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Retrieves a list of calendar resources for an account.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "directory.resources.calendars.list",
       "path": "customer/{customer}/resources/calendars",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.resource.calendar",
        "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates a calendar resource. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "directory.resources.calendars.patch",
       "path": "customer/{customer}/resources/calendars/{calendarResourceId}",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.resource.calendar"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates a calendar resource.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "directory.resources.calendars.update",
       "path": "customer/{customer}/resources/calendars/{calendarResourceId}",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.resource.calendar"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "roleAssignments": {
   "methods": {
    "delete": {
     "description": "Deletes a role assignment.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.roleAssignments.delete",
     "path": "customer/{customer}/roleassignments/{roleAssignmentId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieve a role assignment.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.roleAssignments.get",
     "path": "customer/{customer}/roleassignments/{roleAssignmentId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement",
      "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a role assignment.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.roleAssignments.insert",
     "path": "customer/{customer}/roleassignments",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a paginated list of all roleAssignments.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.roleAssignments.list",
     "path": "customer/{customer}/roleassignments",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement",
      "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "roles": {
   "methods": {
    "delete": {
     "description": "Deletes a role.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.roles.delete",
     "path": "customer/{customer}/roles/{roleId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieves a role.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.roles.get",
     "path": "customer/{customer}/roles/{roleId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement",
      "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a role.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.roles.insert",
     "path": "customer/{customer}/roles",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a paginated list of all the roles in a domain.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.roles.list",
     "path": "customer/{customer}/roles",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement",
      "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates a role. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.roles.patch",
     "path": "customer/{customer}/roles/{roleId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a role.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.roles.update",
     "path": "customer/{customer}/roles/{roleId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.rolemanagement"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "schemas": {
   "methods": {
    "delete": {
     "description": "Delete schema",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.schemas.delete",
     "path": "customer/{customerId}/schemas/{schemaKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.userschema"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieve schema",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.schemas.get",
     "path": "customer/{customerId}/schemas/{schemaKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.userschema",
      "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Create schema.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.schemas.insert",
     "path": "customer/{customerId}/schemas",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.userschema"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieve all schemas for a customer",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.schemas.list",
     "path": "customer/{customerId}/schemas",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.userschema",
      "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Update schema. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.schemas.patch",
     "path": "customer/{customerId}/schemas/{schemaKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.userschema"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update schema",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.schemas.update",
     "path": "customer/{customerId}/schemas/{schemaKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.userschema"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "tokens": {
   "methods": {
    "delete": {
     "description": "Delete all access tokens issued by a user for an application.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.tokens.delete",
     "path": "users/{userKey}/tokens/{clientId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Get information about an access token issued by a user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.tokens.get",
     "path": "users/{userKey}/tokens/{clientId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns the set of tokens specified user has issued to 3rd party applications.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.tokens.list",
     "path": "users/{userKey}/tokens",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "users": {
   "methods": {
    "delete": {
     "description": "Delete user",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "directory.users.delete",
     "path": "users/{userKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "retrieve user",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.users.get",
     "path": "users/{userKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/admin.directory.user.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "create user.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.users.insert",
     "path": "users",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieve either deleted users or all users in a domain (paginated)",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.users.list",
     "path": "users",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/admin.directory.user.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "makeAdmin": {
     "description": "change admin status of a user",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.users.makeAdmin",
     "path": "users/{userKey}/makeAdmin",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "update user. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "directory.users.patch",
     "path": "users/{userKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "undelete": {
     "description": "Undelete a deleted user",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.users.undelete",
     "path": "users/{userKey}/undelete",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "update user",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "directory.users.update",
     "path": "users/{userKey}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "watch": {
     "description": "Watch for changes in users list",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.users.watch",
     "path": "users/watch",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/admin.directory.user.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "aliases": {
     "methods": {
      "delete": {
       "description": "Remove a alias for the user",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "directory.users.aliases.delete",
       "path": "users/{userKey}/aliases/{alias}",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.alias"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Add a alias for the user",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "directory.users.aliases.insert",
       "path": "users/{userKey}/aliases",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.alias"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "List all aliases for a user",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "directory.users.aliases.list",
       "path": "users/{userKey}/aliases",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.alias",
        "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
        "https://www.googleapis.com/auth/admin.directory.user.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": true,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "watch": {
       "description": "Watch for changes in user aliases list",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "directory.users.aliases.watch",
       "path": "users/{userKey}/aliases/watch",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.alias",
        "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
        "https://www.googleapis.com/auth/admin.directory.user.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": true,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "photos": {
     "methods": {
      "delete": {
       "description": "Remove photos for the user",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "directory.users.photos.delete",
       "path": "users/{userKey}/photos/thumbnail",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Retrieve photo of a user",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "directory.users.photos.get",
       "path": "users/{userKey}/photos/thumbnail",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user",
        "https://www.googleapis.com/auth/admin.directory.user.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Add a photo for the user. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "directory.users.photos.patch",
       "path": "users/{userKey}/photos/thumbnail",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Add a photo for the user",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "directory.users.photos.update",
       "path": "users/{userKey}/photos/thumbnail",
       "scopes": [
        "https://www.googleapis.com/auth/admin.directory.user"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "verificationCodes": {
   "methods": {
    "generate": {
     "description": "Generate new backup verification codes for the user.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.verificationCodes.generate",
     "path": "users/{userKey}/verificationCodes/generate",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "invalidate": {
     "description": "Invalidate the current backup verification codes for the user.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "directory.verificationCodes.invalidate",
     "path": "users/{userKey}/verificationCodes/invalidate",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns the current set of valid backup verification codes for the specified user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "directory.verificationCodes.list",
     "path": "users/{userKey}/verificationCodes",
     "scopes": [
      "https://www.googleapis.com/auth/admin.directory.user.security"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20170830",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "admin/directory/v1/",
 "title": "Admin Directory API",
 "version": "directory_v1",
 "version_module": null
}