{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/admin.datatransfer": {
     "description": "View and manage data transfers between users in your organization"
    },
    "https://www.googleapis.com/auth/admin.datatransfer.readonly": {
     "description": "View data transfers between users in your organization"
    }
   }
  }
 },
 "basePath": "/admin/datatransfer/v1/",
 "baseUrl": "https://www.googleapis.com/admin/datatransfer/v1/",
 "batchPath": "batch/admin/datatransfer_v1",
 "canonicalName": "DataTransfer",
 "description": "Transfers user data from one user to another.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/admin-sdk/data-transfer/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/69RNEuIs-2cMvhRHgpkaoTAmcFU\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "admin:datatransfer_v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "admin",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": "admin",
 "protocol": "rest",
 "resources": {
  "applications": {
   "methods": {
    "get": {
     "description": "Retrieves information about an application for the given application ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "datatransfer.applications.get",
     "path": "applications/{applicationId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer",
      "https://www.googleapis.com/auth/admin.datatransfer.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists the applications available for data transfer for a customer.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "datatransfer.applications.list",
     "path": "applications",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer",
      "https://www.googleapis.com/auth/admin.datatransfer.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "transfers": {
   "methods": {
    "get": {
     "description": "Retrieves a data transfer request by its resource ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "datatransfer.transfers.get",
     "path": "transfers/{dataTransferId}",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer",
      "https://www.googleapis.com/auth/admin.datatransfer.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a data transfer request.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "datatransfer.transfers.insert",
     "path": "transfers",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists the transfers for a customer by source user, destination user, or status.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "datatransfer.transfers.list",
     "path": "transfers",
     "scopes": [
      "https://www.googleapis.com/auth/admin.datatransfer",
      "https://www.googleapis.com/auth/admin.datatransfer.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20160223",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "admin/datatransfer/v1/",
 "title": "Admin Data Transfer API",
 "version": "datatransfer_v1",
 "version_module": null
}