{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/analytics": {
     "description": "View and manage your Google Analytics data"
    },
    "https://www.googleapis.com/auth/analytics.edit": {
     "description": "Edit Google Analytics management entities"
    },
    "https://www.googleapis.com/auth/analytics.manage.users": {
     "description": "Manage Google Analytics Account users by email address"
    },
    "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
     "description": "View Google Analytics user permissions"
    },
    "https://www.googleapis.com/auth/analytics.provision": {
     "description": "Create a new Google Analytics account along with its default property and view"
    },
    "https://www.googleapis.com/auth/analytics.readonly": {
     "description": "View your Google Analytics data"
    }
   }
  }
 },
 "basePath": "/analytics/v3/",
 "baseUrl": "https://www.googleapis.com/analytics/v3/",
 "batchPath": "batch/analytics/v3",
 "canonicalName": null,
 "description": "Views and manages your Google Analytics data.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/analytics/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/DSG2TEF18bxTdYooKf_C2-FmmME\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "analytics:v3",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "analytics",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "data": {
   "methods": null,
   "resources": {
    "ga": {
     "methods": {
      "get": {
       "description": "Returns Analytics data for a view (profile).",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.data.ga.get",
       "path": "data/ga",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "mcf": {
     "methods": {
      "get": {
       "description": "Returns Analytics Multi-Channel Funnels data for a view (profile).",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.data.mcf.get",
       "path": "data/mcf",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "realtime": {
     "methods": {
      "get": {
       "description": "Returns real time data for a view (profile).",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.data.realtime.get",
       "path": "data/realtime",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "management": {
   "methods": null,
   "resources": {
    "accountSummaries": {
     "methods": {
      "list": {
       "description": "Lists account summaries (lightweight tree comprised of accounts/properties/profiles) to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.accountSummaries.list",
       "path": "management/accountSummaries",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "accountUserLinks": {
     "methods": {
      "delete": {
       "description": "Removes a user from the given account.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.accountUserLinks.delete",
       "path": "management/accounts/{accountId}/entityUserLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Adds a new user to the given account.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.accountUserLinks.insert",
       "path": "management/accounts/{accountId}/entityUserLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists account-user links for a given account.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.accountUserLinks.list",
       "path": "management/accounts/{accountId}/entityUserLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users",
        "https://www.googleapis.com/auth/analytics.manage.users.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates permissions for an existing user on the given account.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.accountUserLinks.update",
       "path": "management/accounts/{accountId}/entityUserLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "accounts": {
     "methods": {
      "list": {
       "description": "Lists all accounts to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.accounts.list",
       "path": "management/accounts",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "customDataSources": {
     "methods": {
      "list": {
       "description": "List custom data sources to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.customDataSources.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "customDimensions": {
     "methods": {
      "get": {
       "description": "Get a custom dimension to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.customDimensions.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new custom dimension.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.customDimensions.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists custom dimensions to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.customDimensions.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates an existing custom dimension. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.customDimensions.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates an existing custom dimension.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.customDimensions.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "customMetrics": {
     "methods": {
      "get": {
       "description": "Get a custom metric to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.customMetrics.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new custom metric.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.customMetrics.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists custom metrics to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.customMetrics.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates an existing custom metric. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.customMetrics.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates an existing custom metric.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.customMetrics.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "experiments": {
     "methods": {
      "delete": {
       "description": "Delete an experiment.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.experiments.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns an experiment to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.experiments.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new experiment.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.experiments.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists experiments to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.experiments.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Update an existing experiment. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.experiments.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Update an existing experiment.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.experiments.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "filters": {
     "methods": {
      "delete": {
       "description": "Delete a filter.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.filters.delete",
       "path": "management/accounts/{accountId}/filters/{filterId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns a filters to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.filters.get",
       "path": "management/accounts/{accountId}/filters/{filterId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new filter.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.filters.insert",
       "path": "management/accounts/{accountId}/filters",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists all filters for an account",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.filters.list",
       "path": "management/accounts/{accountId}/filters",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates an existing filter. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.filters.patch",
       "path": "management/accounts/{accountId}/filters/{filterId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates an existing filter.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.filters.update",
       "path": "management/accounts/{accountId}/filters/{filterId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "goals": {
     "methods": {
      "get": {
       "description": "Gets a goal to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.goals.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new goal.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.goals.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists goals to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.goals.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates an existing goal. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.goals.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates an existing goal.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.goals.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "profileFilterLinks": {
     "methods": {
      "delete": {
       "description": "Delete a profile filter link.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.profileFilterLinks.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns a single profile filter link.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.profileFilterLinks.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new profile filter link.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.profileFilterLinks.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists all profile filter links for a profile.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.profileFilterLinks.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Update an existing profile filter link. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.profileFilterLinks.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Update an existing profile filter link.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.profileFilterLinks.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "profileUserLinks": {
     "methods": {
      "delete": {
       "description": "Removes a user from the given view (profile).",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.profileUserLinks.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Adds a new user to the given view (profile).",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.profileUserLinks.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists profile-user links for a given view (profile).",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.profileUserLinks.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users",
        "https://www.googleapis.com/auth/analytics.manage.users.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates permissions for an existing user on the given view (profile).",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.profileUserLinks.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "profiles": {
     "methods": {
      "delete": {
       "description": "Deletes a view (profile).",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.profiles.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets a view (profile) to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.profiles.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new view (profile).",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.profiles.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists views (profiles) to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.profiles.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates an existing view (profile). This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.profiles.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates an existing view (profile).",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.profiles.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "remarketingAudience": {
     "methods": {
      "delete": {
       "description": "Delete a remarketing audience.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.remarketingAudience.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets a remarketing audience to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.remarketingAudience.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Creates a new remarketing audience.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.remarketingAudience.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists remarketing audiences to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.remarketingAudience.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates an existing remarketing audience. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.remarketingAudience.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates an existing remarketing audience.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.remarketingAudience.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "segments": {
     "methods": {
      "list": {
       "description": "Lists segments to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.segments.list",
       "path": "management/segments",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "unsampledReports": {
     "methods": {
      "delete": {
       "description": "Deletes an unsampled report.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.unsampledReports.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns a single unsampled report.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.unsampledReports.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new unsampled report.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.unsampledReports.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists unsampled reports to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.unsampledReports.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "uploads": {
     "methods": {
      "deleteUploadData": {
       "description": "Delete data associated with a previous upload.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.uploads.deleteUploadData",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/deleteUploadData",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "List uploads to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.uploads.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads/{uploadId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "List uploads to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.uploads.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "uploadData": {
       "description": "Upload data for a custom data source.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.uploads.uploadData",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": true,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "webPropertyAdWordsLinks": {
     "methods": {
      "delete": {
       "description": "Deletes a web property-AdWords link.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.webPropertyAdWordsLinks.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns a web property-AdWords link to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.webPropertyAdWordsLinks.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Creates a webProperty-AdWords link.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.webPropertyAdWordsLinks.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists webProperty-AdWords links for a given web property.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.webPropertyAdWordsLinks.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates an existing webProperty-AdWords link. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.webPropertyAdWordsLinks.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates an existing webProperty-AdWords link.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.webPropertyAdWordsLinks.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "webproperties": {
     "methods": {
      "get": {
       "description": "Gets a web property to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.webproperties.get",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Create a new property if the account has fewer than 20 properties. Web properties are visible in the Google Analytics interface only if they have at least one profile.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.webproperties.insert",
       "path": "management/accounts/{accountId}/webproperties",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists web properties to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.webproperties.list",
       "path": "management/accounts/{accountId}/webproperties",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates an existing web property. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "analytics.management.webproperties.patch",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates an existing web property.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.webproperties.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.edit"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "webpropertyUserLinks": {
     "methods": {
      "delete": {
       "description": "Removes a user from the given web property.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "analytics.management.webpropertyUserLinks.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Adds a new user to the given web property.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "analytics.management.webpropertyUserLinks.insert",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists webProperty-user links for a given web property.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.webpropertyUserLinks.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users",
        "https://www.googleapis.com/auth/analytics.manage.users.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates permissions for an existing user on the given web property.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "analytics.management.webpropertyUserLinks.update",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}",
       "scopes": [
        "https://www.googleapis.com/auth/analytics.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "metadata": {
   "methods": null,
   "resources": {
    "columns": {
     "methods": {
      "list": {
       "description": "Lists all columns for a report type",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.metadata.columns.list",
       "path": "metadata/{reportType}/columns",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.edit",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "provisioning": {
   "methods": {
    "createAccountTicket": {
     "description": "Creates an account ticket.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "analytics.provisioning.createAccountTicket",
     "path": "provisioning/createAccountTicket",
     "scopes": [
      "https://www.googleapis.com/auth/analytics.provision"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20170807",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "analytics/v3/",
 "title": "Google Analytics API",
 "version": "v3",
 "version_module": null
}