{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/analytics": {
     "description": "View and manage your Google Analytics data"
    },
    "https://www.googleapis.com/auth/analytics.readonly": {
     "description": "View your Google Analytics data"
    }
   }
  }
 },
 "basePath": "/analytics/v2.4/",
 "baseUrl": "https://www.googleapis.com/analytics/v2.4/",
 "batchPath": "batch/analytics/v2.4",
 "canonicalName": null,
 "description": "Views and manages your Google Analytics data.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/analytics/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/kYN47VW3boRYzE7pkj4HK3FyEC0\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "analytics:v2.4",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "analytics",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "data": {
   "methods": {
    "get": {
     "description": "Returns Analytics report data for a view (profile).",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "analytics.data.get",
     "path": "data",
     "scopes": [
      "https://www.googleapis.com/auth/analytics",
      "https://www.googleapis.com/auth/analytics.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "management": {
   "methods": null,
   "resources": {
    "accounts": {
     "methods": {
      "list": {
       "description": "Lists all accounts to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.accounts.list",
       "path": "management/accounts",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "goals": {
     "methods": {
      "list": {
       "description": "Lists goals to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.goals.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "profiles": {
     "methods": {
      "list": {
       "description": "Lists views (profiles) to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.profiles.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "segments": {
     "methods": {
      "list": {
       "description": "Lists advanced segments to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.segments.list",
       "path": "management/segments",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "webproperties": {
     "methods": {
      "list": {
       "description": "Lists web properties to which the user has access.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "analytics.management.webproperties.list",
       "path": "management/accounts/{accountId}/webproperties",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20170807",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "analytics/v2.4/",
 "title": "Google Analytics API",
 "version": "v2.4",
 "version_module": null
}