{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/activity": {
     "description": "View the activity history of your Google apps"
    },
    "https://www.googleapis.com/auth/drive": {
     "description": "View and manage the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.metadata": {
     "description": "View and manage metadata of files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.metadata.readonly": {
     "description": "View metadata for files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.readonly": {
     "description": "View the files in your Google Drive"
    }
   }
  }
 },
 "basePath": "/appsactivity/v1/",
 "baseUrl": "https://www.googleapis.com/appsactivity/v1/",
 "batchPath": "batch/appsactivity/v1",
 "canonicalName": null,
 "description": "Provides a historical view of activity.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/google-apps/activity/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/kFAnMJNmaN64ynO6wl0fvbppm7Y\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "appsactivity:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "appsactivity",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "activities": {
   "methods": {
    "list": {
     "description": "Returns a list of activities visible to the current logged in user. Visible activities are determined by the visiblity settings of the object that was acted on, e.g. Drive files a user can see. An activity is a record of past events. Multiple events may be merged if they are similar. A request is scoped to activities from a given Google service using the source parameter.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "appsactivity.activities.list",
     "path": "activities",
     "scopes": [
      "https://www.googleapis.com/auth/activity",
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.metadata",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20170926",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "appsactivity/v1/",
 "title": "G Suite Activity API",
 "version": "v1",
 "version_module": null
}