{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/blogger": {
     "description": "Manage your Blogger account"
    },
    "https://www.googleapis.com/auth/blogger.readonly": {
     "description": "View your Blogger account"
    }
   }
  }
 },
 "basePath": "/blogger/v3/",
 "baseUrl": "https://www.googleapis.com/blogger/v3/",
 "batchPath": "batch",
 "canonicalName": null,
 "description": "API for access to the data within Blogger.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/blogger/docs/3.0/getting_started",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/Goh5bsNuqq7lTY-yMf_QcKSL760\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "blogger:v3",
 "kind": "discovery#restDescription",
 "labels": [
  "limited_availability"
 ],
 "methods": null,
 "name": "blogger",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "blogUserInfos": {
   "methods": {
    "get": {
     "description": "Gets one blog and user info pair by blogId and userId.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.blogUserInfos.get",
     "path": "users/{userId}/blogs/{blogId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "blogs": {
   "methods": {
    "get": {
     "description": "Gets one blog by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.blogs.get",
     "path": "blogs/{blogId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getByUrl": {
     "description": "Retrieve a Blog by URL.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.blogs.getByUrl",
     "path": "blogs/byurl",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "listByUser": {
     "description": "Retrieves a list of blogs, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.blogs.listByUser",
     "path": "users/{userId}/blogs",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "comments": {
   "methods": {
    "approve": {
     "description": "Marks a comment as not spam.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.comments.approve",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/approve",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Delete a comment by ID.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "blogger.comments.delete",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one comment by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.comments.get",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the comments for a post, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.comments.list",
     "path": "blogs/{blogId}/posts/{postId}/comments",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "listByBlog": {
     "description": "Retrieves the comments for a blog, across all posts, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.comments.listByBlog",
     "path": "blogs/{blogId}/comments",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "markAsSpam": {
     "description": "Marks a comment as spam.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.comments.markAsSpam",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/spam",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "removeContent": {
     "description": "Removes the content of a comment.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.comments.removeContent",
     "path": "blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "pageViews": {
   "methods": {
    "get": {
     "description": "Retrieve pageview stats for a Blog.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.pageViews.get",
     "path": "blogs/{blogId}/pageviews",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "pages": {
   "methods": {
    "delete": {
     "description": "Delete a page by ID.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "blogger.pages.delete",
     "path": "blogs/{blogId}/pages/{pageId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one blog page by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.pages.get",
     "path": "blogs/{blogId}/pages/{pageId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Add a page.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.pages.insert",
     "path": "blogs/{blogId}/pages",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the pages for a blog, optionally including non-LIVE statuses.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.pages.list",
     "path": "blogs/{blogId}/pages",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Update a page. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "blogger.pages.patch",
     "path": "blogs/{blogId}/pages/{pageId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "publish": {
     "description": "Publishes a draft page.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.pages.publish",
     "path": "blogs/{blogId}/pages/{pageId}/publish",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "revert": {
     "description": "Revert a published or scheduled page to draft state.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.pages.revert",
     "path": "blogs/{blogId}/pages/{pageId}/revert",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update a page.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "blogger.pages.update",
     "path": "blogs/{blogId}/pages/{pageId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "postUserInfos": {
   "methods": {
    "get": {
     "description": "Gets one post and user info pair, by post ID and user ID. The post user info contains per-user information about the post, such as access rights, specific to the user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.postUserInfos.get",
     "path": "users/{userId}/blogs/{blogId}/posts/{postId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of post and post user info pairs, possibly filtered. The post user info contains per-user information about the post, such as access rights, specific to the user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.postUserInfos.list",
     "path": "users/{userId}/blogs/{blogId}/posts",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "posts": {
   "methods": {
    "delete": {
     "description": "Delete a post by ID.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "blogger.posts.delete",
     "path": "blogs/{blogId}/posts/{postId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Get a post by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.posts.get",
     "path": "blogs/{blogId}/posts/{postId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getByPath": {
     "description": "Retrieve a Post by Path.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.posts.getByPath",
     "path": "blogs/{blogId}/posts/bypath",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Add a post.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.posts.insert",
     "path": "blogs/{blogId}/posts",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of posts, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.posts.list",
     "path": "blogs/{blogId}/posts",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Update a post. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "blogger.posts.patch",
     "path": "blogs/{blogId}/posts/{postId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "publish": {
     "description": "Publishes a draft post, optionally at the specific time of the given publishDate parameter.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.posts.publish",
     "path": "blogs/{blogId}/posts/{postId}/publish",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "revert": {
     "description": "Revert a published or scheduled post to draft state.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "blogger.posts.revert",
     "path": "blogs/{blogId}/posts/{postId}/revert",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "search": {
     "description": "Search for a post.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.posts.search",
     "path": "blogs/{blogId}/posts/search",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update a post.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "blogger.posts.update",
     "path": "blogs/{blogId}/posts/{postId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "users": {
   "methods": {
    "get": {
     "description": "Gets one user by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "blogger.users.get",
     "path": "users/{userId}",
     "scopes": [
      "https://www.googleapis.com/auth/blogger",
      "https://www.googleapis.com/auth/blogger.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20150422",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "blogger/v3/",
 "title": "Blogger API",
 "version": "v3",
 "version_module": null
}