{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/calendar": {
     "description": "Manage your calendars"
    },
    "https://www.googleapis.com/auth/calendar.readonly": {
     "description": "View your calendars"
    }
   }
  }
 },
 "basePath": "/calendar/v3/",
 "baseUrl": "https://www.googleapis.com/calendar/v3/",
 "batchPath": "batch/calendar/v3",
 "canonicalName": null,
 "description": "Manipulates events and other calendar data.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/google-apps/calendar/firstapp",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/2j8D2nFUEmPd5-ldLWN3HdwZdb0\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "calendar:v3",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "calendar",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "acl": {
   "methods": {
    "delete": {
     "description": "Deletes an access control rule.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "calendar.acl.delete",
     "path": "calendars/{calendarId}/acl/{ruleId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns an access control rule.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.acl.get",
     "path": "calendars/{calendarId}/acl/{ruleId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates an access control rule.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.acl.insert",
     "path": "calendars/{calendarId}/acl",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns the rules in the access control list for the calendar.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.acl.list",
     "path": "calendars/{calendarId}/acl",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an access control rule. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "calendar.acl.patch",
     "path": "calendars/{calendarId}/acl/{ruleId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an access control rule.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "calendar.acl.update",
     "path": "calendars/{calendarId}/acl/{ruleId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "watch": {
     "description": "Watch for changes to ACL resources.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.acl.watch",
     "path": "calendars/{calendarId}/acl/watch",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "calendarList": {
   "methods": {
    "delete": {
     "description": "Deletes an entry on the user's calendar list.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "calendar.calendarList.delete",
     "path": "users/me/calendarList/{calendarId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns an entry on the user's calendar list.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.calendarList.get",
     "path": "users/me/calendarList/{calendarId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Adds an entry to the user's calendar list.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.calendarList.insert",
     "path": "users/me/calendarList",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns entries on the user's calendar list.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.calendarList.list",
     "path": "users/me/calendarList",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an entry on the user's calendar list. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "calendar.calendarList.patch",
     "path": "users/me/calendarList/{calendarId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an entry on the user's calendar list.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "calendar.calendarList.update",
     "path": "users/me/calendarList/{calendarId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "watch": {
     "description": "Watch for changes to CalendarList resources.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.calendarList.watch",
     "path": "users/me/calendarList/watch",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "calendars": {
   "methods": {
    "clear": {
     "description": "Clears a primary calendar. This operation deletes all events associated with the primary calendar of an account.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.calendars.clear",
     "path": "calendars/{calendarId}/clear",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Deletes a secondary calendar. Use calendars.clear for clearing all events on primary calendars.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "calendar.calendars.delete",
     "path": "calendars/{calendarId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns metadata for a calendar.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.calendars.get",
     "path": "calendars/{calendarId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a secondary calendar.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.calendars.insert",
     "path": "calendars",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates metadata for a calendar. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "calendar.calendars.patch",
     "path": "calendars/{calendarId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates metadata for a calendar.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "calendar.calendars.update",
     "path": "calendars/{calendarId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "channels": {
   "methods": {
    "stop": {
     "description": "Stop watching resources through this channel",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.channels.stop",
     "path": "channels/stop",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "colors": {
   "methods": {
    "get": {
     "description": "Returns the color definitions for calendars and events.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.colors.get",
     "path": "colors",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "events": {
   "methods": {
    "delete": {
     "description": "Deletes an event.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "calendar.events.delete",
     "path": "calendars/{calendarId}/events/{eventId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns an event.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.events.get",
     "path": "calendars/{calendarId}/events/{eventId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "import": {
     "description": "Imports an event. This operation is used to add a private copy of an existing event to a calendar.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.events.import",
     "path": "calendars/{calendarId}/events/import",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates an event.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.events.insert",
     "path": "calendars/{calendarId}/events",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "instances": {
     "description": "Returns instances of the specified recurring event.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.events.instances",
     "path": "calendars/{calendarId}/events/{eventId}/instances",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns events on the specified calendar.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.events.list",
     "path": "calendars/{calendarId}/events",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "move": {
     "description": "Moves an event to another calendar, i.e. changes an event's organizer.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.events.move",
     "path": "calendars/{calendarId}/events/{eventId}/move",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an event. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "calendar.events.patch",
     "path": "calendars/{calendarId}/events/{eventId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "quickAdd": {
     "description": "Creates an event based on a simple text string.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.events.quickAdd",
     "path": "calendars/{calendarId}/events/quickAdd",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an event.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "calendar.events.update",
     "path": "calendars/{calendarId}/events/{eventId}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "watch": {
     "description": "Watch for changes to Events resources.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.events.watch",
     "path": "calendars/{calendarId}/events/watch",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "freebusy": {
   "methods": {
    "query": {
     "description": "Returns free/busy information for a set of calendars.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.freebusy.query",
     "path": "freeBusy",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "settings": {
   "methods": {
    "get": {
     "description": "Returns a single user setting.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.settings.get",
     "path": "users/me/settings/{setting}",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns all user settings for the authenticated user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "calendar.settings.list",
     "path": "users/me/settings",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "watch": {
     "description": "Watch for changes to Settings resources.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "calendar.settings.watch",
     "path": "users/me/settings/watch",
     "scopes": [
      "https://www.googleapis.com/auth/calendar",
      "https://www.googleapis.com/auth/calendar.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20170924",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "calendar/v3/",
 "title": "Calendar API",
 "version": "v3",
 "version_module": null
}