{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/cloud-platform.read-only": {
     "description": "View your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/cloud.useraccounts": {
     "description": "Manage your Google Cloud User Accounts"
    },
    "https://www.googleapis.com/auth/cloud.useraccounts.readonly": {
     "description": "View your Google Cloud User Accounts"
    }
   }
  }
 },
 "basePath": "/clouduseraccounts/alpha/projects/",
 "baseUrl": "https://www.googleapis.com/clouduseraccounts/alpha/projects/",
 "batchPath": "batch/clouduseraccounts/alpha",
 "canonicalName": "Cloud User Accounts",
 "description": "Creates and manages users and groups for accessing Google Compute Engine virtual machines.",
 "discoveryVersion": "v1",
 "documentationLink": "https://cloud.google.com/compute/docs/access/user-accounts/api/latest/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/lOQeocShB0dxGwrtxzB56jZ95Xk\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "clouduseraccounts:alpha",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "clouduseraccounts",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "globalAccountsOperations": {
   "methods": {
    "delete": {
     "description": "Deletes the specified operation resource.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "clouduseraccounts.globalAccountsOperations.delete",
     "path": "{project}/global/operations/{operation}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieves the specified operation resource.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "clouduseraccounts.globalAccountsOperations.get",
     "path": "{project}/global/operations/{operation}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the list of operation resources contained within the specified project.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "clouduseraccounts.globalAccountsOperations.list",
     "path": "{project}/global/operations",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "groups": {
   "methods": {
    "addMember": {
     "description": "Adds users to the specified group.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.groups.addMember",
     "path": "{project}/global/groups/{groupName}/addMember",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Deletes the specified Group resource.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "clouduseraccounts.groups.delete",
     "path": "{project}/global/groups/{groupName}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns the specified Group resource.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "clouduseraccounts.groups.get",
     "path": "{project}/global/groups/{groupName}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getIamPolicy": {
     "description": "Gets the access control policy for a resource. May be empty if no such policy or resource exists.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "clouduseraccounts.groups.getIamPolicy",
     "path": "{project}/global/groups/{resource}/getIamPolicy",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a Group resource in the specified project using the data included in the request.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.groups.insert",
     "path": "{project}/global/groups",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the list of groups contained within the specified project.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "clouduseraccounts.groups.list",
     "path": "{project}/global/groups",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "removeMember": {
     "description": "Removes users from the specified group.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.groups.removeMember",
     "path": "{project}/global/groups/{groupName}/removeMember",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "setIamPolicy": {
     "description": "Sets the access control policy on the specified resource. Replaces any existing policy.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.groups.setIamPolicy",
     "path": "{project}/global/groups/{resource}/setIamPolicy",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "testIamPermissions": {
     "description": "Returns permissions that a caller has on the specified resource.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.groups.testIamPermissions",
     "path": "{project}/global/groups/{resource}/testIamPermissions",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "linux": {
   "methods": {
    "getAuthorizedKeysView": {
     "description": "Returns a list of authorized public keys for a specific user account.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.linux.getAuthorizedKeysView",
     "path": "{project}/zones/{zone}/authorizedKeysView/{user}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getLinuxAccountViews": {
     "description": "Retrieves a list of user accounts for an instance within a specific project.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.linux.getLinuxAccountViews",
     "path": "{project}/zones/{zone}/linuxAccountViews",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "users": {
   "methods": {
    "addPublicKey": {
     "description": "Adds a public key to the specified User resource with the data included in the request.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.users.addPublicKey",
     "path": "{project}/global/users/{user}/addPublicKey",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Deletes the specified User resource.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "clouduseraccounts.users.delete",
     "path": "{project}/global/users/{user}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns the specified User resource.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "clouduseraccounts.users.get",
     "path": "{project}/global/users/{user}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getIamPolicy": {
     "description": "Gets the access control policy for a resource. May be empty if no such policy or resource exists.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "clouduseraccounts.users.getIamPolicy",
     "path": "{project}/global/users/{resource}/getIamPolicy",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a User resource in the specified project using the data included in the request.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.users.insert",
     "path": "{project}/global/users",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of users contained within the specified project.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "clouduseraccounts.users.list",
     "path": "{project}/global/users",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "removePublicKey": {
     "description": "Removes the specified public key from the user.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.users.removePublicKey",
     "path": "{project}/global/users/{user}/removePublicKey",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud.useraccounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "setIamPolicy": {
     "description": "Sets the access control policy on the specified resource. Replaces any existing policy.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.users.setIamPolicy",
     "path": "{project}/global/users/{resource}/setIamPolicy",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "testIamPermissions": {
     "description": "Returns permissions that a caller has on the specified resource.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "clouduseraccounts.users.testIamPermissions",
     "path": "{project}/global/users/{resource}/testIamPermissions",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/cloud.useraccounts",
      "https://www.googleapis.com/auth/cloud.useraccounts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20160316",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "clouduseraccounts/alpha/projects/",
 "title": "Cloud User Accounts API",
 "version": "alpha",
 "version_module": null
}