{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/consumersurveys": {
     "description": "View and edit your surveys and results"
    },
    "https://www.googleapis.com/auth/consumersurveys.readonly": {
     "description": "View the results for your surveys"
    },
    "https://www.googleapis.com/auth/userinfo.email": {
     "description": "View your email address"
    }
   }
  }
 },
 "basePath": "/consumersurveys/v2/",
 "baseUrl": "https://www.googleapis.com/consumersurveys/v2/",
 "batchPath": "batch/consumersurveys/v2",
 "canonicalName": "Consumer Surveys",
 "description": "Creates and conducts surveys, lists the surveys that an authenticated user owns, and retrieves survey results and information about specified surveys.",
 "discoveryVersion": "v1",
 "documentationLink": null,
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/e7DEYLH6SdmU14auNlU-9VK4HgU\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "consumersurveys:v2",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "consumersurveys",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "mobileapppanels": {
   "methods": {
    "get": {
     "description": "Retrieves a MobileAppPanel that is available to the authenticated user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "consumersurveys.mobileapppanels.get",
     "path": "mobileAppPanels/{panelId}",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/consumersurveys.readonly",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists the MobileAppPanels available to the authenticated user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "consumersurveys.mobileapppanels.list",
     "path": "mobileAppPanels",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/consumersurveys.readonly",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a MobileAppPanel. Currently the only property that can be updated is the owners property.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "consumersurveys.mobileapppanels.update",
     "path": "mobileAppPanels/{panelId}",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "results": {
   "methods": {
    "get": {
     "description": "Retrieves any survey results that have been produced so far. Results are formatted as an Excel file. You must add \"?alt=media\" to the URL as an argument to get results.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "consumersurveys.results.get",
     "path": "surveys/{surveyUrlId}/results",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/consumersurveys.readonly",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": true,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "surveys": {
   "methods": {
    "delete": {
     "description": "Removes a survey from view in all user GET requests.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "consumersurveys.surveys.delete",
     "path": "surveys/{surveyUrlId}",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieves information about the specified survey.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "consumersurveys.surveys.get",
     "path": "surveys/{surveyUrlId}",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/consumersurveys.readonly",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a survey.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "consumersurveys.surveys.insert",
     "path": "surveys",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists the surveys owned by the authenticated user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "consumersurveys.surveys.list",
     "path": "surveys",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/consumersurveys.readonly",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "start": {
     "description": "Begins running a survey.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "consumersurveys.surveys.start",
     "path": "surveys/{resourceId}/start",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "stop": {
     "description": "Stops a running survey.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "consumersurveys.surveys.stop",
     "path": "surveys/{resourceId}/stop",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a survey. Currently the only property that can be updated is the owners property.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "consumersurveys.surveys.update",
     "path": "surveys/{surveyUrlId}",
     "scopes": [
      "https://www.googleapis.com/auth/consumersurveys",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20170407",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "consumersurveys/v2/",
 "title": "Consumer Surveys API",
 "version": "v2",
 "version_module": null
}