{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/ddmconversions": {
     "description": "Manage DoubleClick Digital Marketing conversions"
    },
    "https://www.googleapis.com/auth/dfareporting": {
     "description": "View and manage DoubleClick for Advertisers reports"
    },
    "https://www.googleapis.com/auth/dfatrafficking": {
     "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
    }
   }
  }
 },
 "basePath": "/dfareporting/v2.8/",
 "baseUrl": "https://www.googleapis.com/dfareporting/v2.8/",
 "batchPath": "batch/dfareporting/v2.8",
 "canonicalName": null,
 "description": "Manages your DoubleClick Campaign Manager ad campaigns and reports.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/emGV_y_FRSYhyMgSPP7gVElVBpw\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "dfareporting:v2.8",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "dfareporting",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "accountActiveAdSummaries": {
   "methods": {
    "get": {
     "description": "Gets the account's active ad summary by account ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accountActiveAdSummaries.get",
     "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "accountPermissionGroups": {
   "methods": {
    "get": {
     "description": "Gets one account permission group by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accountPermissionGroups.get",
     "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the list of account permission groups.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accountPermissionGroups.list",
     "path": "userprofiles/{profileId}/accountPermissionGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "accountPermissions": {
   "methods": {
    "get": {
     "description": "Gets one account permission by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accountPermissions.get",
     "path": "userprofiles/{profileId}/accountPermissions/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the list of account permissions.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accountPermissions.list",
     "path": "userprofiles/{profileId}/accountPermissions",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "accountUserProfiles": {
   "methods": {
    "get": {
     "description": "Gets one account user profile by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accountUserProfiles.get",
     "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new account user profile.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.accountUserProfiles.insert",
     "path": "userprofiles/{profileId}/accountUserProfiles",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accountUserProfiles.list",
     "path": "userprofiles/{profileId}/accountUserProfiles",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing account user profile. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.accountUserProfiles.patch",
     "path": "userprofiles/{profileId}/accountUserProfiles",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing account user profile.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.accountUserProfiles.update",
     "path": "userprofiles/{profileId}/accountUserProfiles",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "accounts": {
   "methods": {
    "get": {
     "description": "Gets one account by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accounts.get",
     "path": "userprofiles/{profileId}/accounts/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.accounts.list",
     "path": "userprofiles/{profileId}/accounts",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing account. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.accounts.patch",
     "path": "userprofiles/{profileId}/accounts",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing account.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.accounts.update",
     "path": "userprofiles/{profileId}/accounts",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "ads": {
   "methods": {
    "get": {
     "description": "Gets one ad by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.ads.get",
     "path": "userprofiles/{profileId}/ads/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new ad.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.ads.insert",
     "path": "userprofiles/{profileId}/ads",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.ads.list",
     "path": "userprofiles/{profileId}/ads",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing ad. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.ads.patch",
     "path": "userprofiles/{profileId}/ads",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing ad.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.ads.update",
     "path": "userprofiles/{profileId}/ads",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "advertiserGroups": {
   "methods": {
    "delete": {
     "description": "Deletes an existing advertiser group.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.advertiserGroups.delete",
     "path": "userprofiles/{profileId}/advertiserGroups/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one advertiser group by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.advertiserGroups.get",
     "path": "userprofiles/{profileId}/advertiserGroups/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new advertiser group.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.advertiserGroups.insert",
     "path": "userprofiles/{profileId}/advertiserGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.advertiserGroups.list",
     "path": "userprofiles/{profileId}/advertiserGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing advertiser group. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.advertiserGroups.patch",
     "path": "userprofiles/{profileId}/advertiserGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing advertiser group.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.advertiserGroups.update",
     "path": "userprofiles/{profileId}/advertiserGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "advertisers": {
   "methods": {
    "get": {
     "description": "Gets one advertiser by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.advertisers.get",
     "path": "userprofiles/{profileId}/advertisers/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new advertiser.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.advertisers.insert",
     "path": "userprofiles/{profileId}/advertisers",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.advertisers.list",
     "path": "userprofiles/{profileId}/advertisers",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing advertiser. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.advertisers.patch",
     "path": "userprofiles/{profileId}/advertisers",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing advertiser.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.advertisers.update",
     "path": "userprofiles/{profileId}/advertisers",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "browsers": {
   "methods": {
    "list": {
     "description": "Retrieves a list of browsers.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.browsers.list",
     "path": "userprofiles/{profileId}/browsers",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "campaignCreativeAssociations": {
   "methods": {
    "insert": {
     "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.campaignCreativeAssociations.insert",
     "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.campaignCreativeAssociations.list",
     "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "campaigns": {
   "methods": {
    "get": {
     "description": "Gets one campaign by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.campaigns.get",
     "path": "userprofiles/{profileId}/campaigns/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new campaign.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.campaigns.insert",
     "path": "userprofiles/{profileId}/campaigns",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.campaigns.list",
     "path": "userprofiles/{profileId}/campaigns",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing campaign. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.campaigns.patch",
     "path": "userprofiles/{profileId}/campaigns",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing campaign.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.campaigns.update",
     "path": "userprofiles/{profileId}/campaigns",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "changeLogs": {
   "methods": {
    "get": {
     "description": "Gets one change log by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.changeLogs.get",
     "path": "userprofiles/{profileId}/changeLogs/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of change logs. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.changeLogs.list",
     "path": "userprofiles/{profileId}/changeLogs",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "cities": {
   "methods": {
    "list": {
     "description": "Retrieves a list of cities, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.cities.list",
     "path": "userprofiles/{profileId}/cities",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "connectionTypes": {
   "methods": {
    "get": {
     "description": "Gets one connection type by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.connectionTypes.get",
     "path": "userprofiles/{profileId}/connectionTypes/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of connection types.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.connectionTypes.list",
     "path": "userprofiles/{profileId}/connectionTypes",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "contentCategories": {
   "methods": {
    "delete": {
     "description": "Deletes an existing content category.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.contentCategories.delete",
     "path": "userprofiles/{profileId}/contentCategories/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one content category by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.contentCategories.get",
     "path": "userprofiles/{profileId}/contentCategories/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new content category.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.contentCategories.insert",
     "path": "userprofiles/{profileId}/contentCategories",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.contentCategories.list",
     "path": "userprofiles/{profileId}/contentCategories",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing content category. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.contentCategories.patch",
     "path": "userprofiles/{profileId}/contentCategories",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing content category.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.contentCategories.update",
     "path": "userprofiles/{profileId}/contentCategories",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "conversions": {
   "methods": {
    "batchinsert": {
     "description": "Inserts conversions.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.conversions.batchinsert",
     "path": "userprofiles/{profileId}/conversions/batchinsert",
     "scopes": [
      "https://www.googleapis.com/auth/ddmconversions"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "batchupdate": {
     "description": "Updates existing conversions.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.conversions.batchupdate",
     "path": "userprofiles/{profileId}/conversions/batchupdate",
     "scopes": [
      "https://www.googleapis.com/auth/ddmconversions"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "countries": {
   "methods": {
    "get": {
     "description": "Gets one country by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.countries.get",
     "path": "userprofiles/{profileId}/countries/{dartId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of countries.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.countries.list",
     "path": "userprofiles/{profileId}/countries",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "creativeAssets": {
   "methods": {
    "insert": {
     "description": "Inserts a new creative asset.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.creativeAssets.insert",
     "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "creativeFieldValues": {
   "methods": {
    "delete": {
     "description": "Deletes an existing creative field value.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.creativeFieldValues.delete",
     "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one creative field value by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.creativeFieldValues.get",
     "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new creative field value.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.creativeFieldValues.insert",
     "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.creativeFieldValues.list",
     "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing creative field value. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.creativeFieldValues.patch",
     "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing creative field value.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.creativeFieldValues.update",
     "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "creativeFields": {
   "methods": {
    "delete": {
     "description": "Deletes an existing creative field.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.creativeFields.delete",
     "path": "userprofiles/{profileId}/creativeFields/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one creative field by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.creativeFields.get",
     "path": "userprofiles/{profileId}/creativeFields/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new creative field.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.creativeFields.insert",
     "path": "userprofiles/{profileId}/creativeFields",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.creativeFields.list",
     "path": "userprofiles/{profileId}/creativeFields",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing creative field. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.creativeFields.patch",
     "path": "userprofiles/{profileId}/creativeFields",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing creative field.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.creativeFields.update",
     "path": "userprofiles/{profileId}/creativeFields",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "creativeGroups": {
   "methods": {
    "get": {
     "description": "Gets one creative group by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.creativeGroups.get",
     "path": "userprofiles/{profileId}/creativeGroups/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new creative group.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.creativeGroups.insert",
     "path": "userprofiles/{profileId}/creativeGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.creativeGroups.list",
     "path": "userprofiles/{profileId}/creativeGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing creative group. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.creativeGroups.patch",
     "path": "userprofiles/{profileId}/creativeGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing creative group.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.creativeGroups.update",
     "path": "userprofiles/{profileId}/creativeGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "creatives": {
   "methods": {
    "get": {
     "description": "Gets one creative by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.creatives.get",
     "path": "userprofiles/{profileId}/creatives/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new creative.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.creatives.insert",
     "path": "userprofiles/{profileId}/creatives",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.creatives.list",
     "path": "userprofiles/{profileId}/creatives",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing creative. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.creatives.patch",
     "path": "userprofiles/{profileId}/creatives",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing creative.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.creatives.update",
     "path": "userprofiles/{profileId}/creatives",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "dimensionValues": {
   "methods": {
    "query": {
     "description": "Retrieves list of report dimension values for a list of filters.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.dimensionValues.query",
     "path": "userprofiles/{profileId}/dimensionvalues/query",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "directorySiteContacts": {
   "methods": {
    "get": {
     "description": "Gets one directory site contact by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.directorySiteContacts.get",
     "path": "userprofiles/{profileId}/directorySiteContacts/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of directory site contacts, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.directorySiteContacts.list",
     "path": "userprofiles/{profileId}/directorySiteContacts",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "directorySites": {
   "methods": {
    "get": {
     "description": "Gets one directory site by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.directorySites.get",
     "path": "userprofiles/{profileId}/directorySites/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new directory site.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.directorySites.insert",
     "path": "userprofiles/{profileId}/directorySites",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.directorySites.list",
     "path": "userprofiles/{profileId}/directorySites",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "dynamicTargetingKeys": {
   "methods": {
    "delete": {
     "description": "Deletes an existing dynamic targeting key.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.dynamicTargetingKeys.delete",
     "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.dynamicTargetingKeys.insert",
     "path": "userprofiles/{profileId}/dynamicTargetingKeys",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of dynamic targeting keys.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.dynamicTargetingKeys.list",
     "path": "userprofiles/{profileId}/dynamicTargetingKeys",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "eventTags": {
   "methods": {
    "delete": {
     "description": "Deletes an existing event tag.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.eventTags.delete",
     "path": "userprofiles/{profileId}/eventTags/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one event tag by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.eventTags.get",
     "path": "userprofiles/{profileId}/eventTags/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new event tag.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.eventTags.insert",
     "path": "userprofiles/{profileId}/eventTags",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of event tags, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.eventTags.list",
     "path": "userprofiles/{profileId}/eventTags",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing event tag. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.eventTags.patch",
     "path": "userprofiles/{profileId}/eventTags",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing event tag.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.eventTags.update",
     "path": "userprofiles/{profileId}/eventTags",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "files": {
   "methods": {
    "get": {
     "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.files.get",
     "path": "reports/{reportId}/files/{fileId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": true,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists files for a user profile.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.files.list",
     "path": "userprofiles/{profileId}/files",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "floodlightActivities": {
   "methods": {
    "delete": {
     "description": "Deletes an existing floodlight activity.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.floodlightActivities.delete",
     "path": "userprofiles/{profileId}/floodlightActivities/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "generatetag": {
     "description": "Generates a tag for a floodlight activity.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.floodlightActivities.generatetag",
     "path": "userprofiles/{profileId}/floodlightActivities/generatetag",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one floodlight activity by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.floodlightActivities.get",
     "path": "userprofiles/{profileId}/floodlightActivities/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new floodlight activity.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.floodlightActivities.insert",
     "path": "userprofiles/{profileId}/floodlightActivities",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.floodlightActivities.list",
     "path": "userprofiles/{profileId}/floodlightActivities",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing floodlight activity. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.floodlightActivities.patch",
     "path": "userprofiles/{profileId}/floodlightActivities",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing floodlight activity.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.floodlightActivities.update",
     "path": "userprofiles/{profileId}/floodlightActivities",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "floodlightActivityGroups": {
   "methods": {
    "get": {
     "description": "Gets one floodlight activity group by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.floodlightActivityGroups.get",
     "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new floodlight activity group.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.floodlightActivityGroups.insert",
     "path": "userprofiles/{profileId}/floodlightActivityGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.floodlightActivityGroups.list",
     "path": "userprofiles/{profileId}/floodlightActivityGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.floodlightActivityGroups.patch",
     "path": "userprofiles/{profileId}/floodlightActivityGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing floodlight activity group.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.floodlightActivityGroups.update",
     "path": "userprofiles/{profileId}/floodlightActivityGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "floodlightConfigurations": {
   "methods": {
    "get": {
     "description": "Gets one floodlight configuration by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.floodlightConfigurations.get",
     "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of floodlight configurations, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.floodlightConfigurations.list",
     "path": "userprofiles/{profileId}/floodlightConfigurations",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.floodlightConfigurations.patch",
     "path": "userprofiles/{profileId}/floodlightConfigurations",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing floodlight configuration.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.floodlightConfigurations.update",
     "path": "userprofiles/{profileId}/floodlightConfigurations",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "inventoryItems": {
   "methods": {
    "get": {
     "description": "Gets one inventory item by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.inventoryItems.get",
     "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.inventoryItems.list",
     "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "landingPages": {
   "methods": {
    "delete": {
     "description": "Deletes an existing campaign landing page.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.landingPages.delete",
     "path": "userprofiles/{profileId}/campaigns/{campaignId}/landingPages/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one campaign landing page by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.landingPages.get",
     "path": "userprofiles/{profileId}/campaigns/{campaignId}/landingPages/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new landing page for the specified campaign.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.landingPages.insert",
     "path": "userprofiles/{profileId}/campaigns/{campaignId}/landingPages",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves the list of landing pages for the specified campaign.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.landingPages.list",
     "path": "userprofiles/{profileId}/campaigns/{campaignId}/landingPages",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing campaign landing page. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.landingPages.patch",
     "path": "userprofiles/{profileId}/campaigns/{campaignId}/landingPages",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing campaign landing page.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.landingPages.update",
     "path": "userprofiles/{profileId}/campaigns/{campaignId}/landingPages",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "languages": {
   "methods": {
    "list": {
     "description": "Retrieves a list of languages.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.languages.list",
     "path": "userprofiles/{profileId}/languages",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "metros": {
   "methods": {
    "list": {
     "description": "Retrieves a list of metros.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.metros.list",
     "path": "userprofiles/{profileId}/metros",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "mobileCarriers": {
   "methods": {
    "get": {
     "description": "Gets one mobile carrier by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.mobileCarriers.get",
     "path": "userprofiles/{profileId}/mobileCarriers/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of mobile carriers.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.mobileCarriers.list",
     "path": "userprofiles/{profileId}/mobileCarriers",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "operatingSystemVersions": {
   "methods": {
    "get": {
     "description": "Gets one operating system version by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.operatingSystemVersions.get",
     "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of operating system versions.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.operatingSystemVersions.list",
     "path": "userprofiles/{profileId}/operatingSystemVersions",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "operatingSystems": {
   "methods": {
    "get": {
     "description": "Gets one operating system by DART ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.operatingSystems.get",
     "path": "userprofiles/{profileId}/operatingSystems/{dartId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of operating systems.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.operatingSystems.list",
     "path": "userprofiles/{profileId}/operatingSystems",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "orderDocuments": {
   "methods": {
    "get": {
     "description": "Gets one order document by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.orderDocuments.get",
     "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.orderDocuments.list",
     "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "orders": {
   "methods": {
    "get": {
     "description": "Gets one order by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.orders.get",
     "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.orders.list",
     "path": "userprofiles/{profileId}/projects/{projectId}/orders",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "placementGroups": {
   "methods": {
    "get": {
     "description": "Gets one placement group by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.placementGroups.get",
     "path": "userprofiles/{profileId}/placementGroups/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new placement group.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.placementGroups.insert",
     "path": "userprofiles/{profileId}/placementGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.placementGroups.list",
     "path": "userprofiles/{profileId}/placementGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing placement group. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.placementGroups.patch",
     "path": "userprofiles/{profileId}/placementGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing placement group.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.placementGroups.update",
     "path": "userprofiles/{profileId}/placementGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "placementStrategies": {
   "methods": {
    "delete": {
     "description": "Deletes an existing placement strategy.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.placementStrategies.delete",
     "path": "userprofiles/{profileId}/placementStrategies/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one placement strategy by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.placementStrategies.get",
     "path": "userprofiles/{profileId}/placementStrategies/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new placement strategy.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.placementStrategies.insert",
     "path": "userprofiles/{profileId}/placementStrategies",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.placementStrategies.list",
     "path": "userprofiles/{profileId}/placementStrategies",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing placement strategy. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.placementStrategies.patch",
     "path": "userprofiles/{profileId}/placementStrategies",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing placement strategy.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.placementStrategies.update",
     "path": "userprofiles/{profileId}/placementStrategies",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "placements": {
   "methods": {
    "generatetags": {
     "description": "Generates tags for a placement.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.placements.generatetags",
     "path": "userprofiles/{profileId}/placements/generatetags",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one placement by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.placements.get",
     "path": "userprofiles/{profileId}/placements/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new placement.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.placements.insert",
     "path": "userprofiles/{profileId}/placements",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.placements.list",
     "path": "userprofiles/{profileId}/placements",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing placement. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.placements.patch",
     "path": "userprofiles/{profileId}/placements",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing placement.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.placements.update",
     "path": "userprofiles/{profileId}/placements",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "platformTypes": {
   "methods": {
    "get": {
     "description": "Gets one platform type by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.platformTypes.get",
     "path": "userprofiles/{profileId}/platformTypes/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of platform types.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.platformTypes.list",
     "path": "userprofiles/{profileId}/platformTypes",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "postalCodes": {
   "methods": {
    "get": {
     "description": "Gets one postal code by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.postalCodes.get",
     "path": "userprofiles/{profileId}/postalCodes/{code}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of postal codes.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.postalCodes.list",
     "path": "userprofiles/{profileId}/postalCodes",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "projects": {
   "methods": {
    "get": {
     "description": "Gets one project by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.projects.get",
     "path": "userprofiles/{profileId}/projects/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of projects, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.projects.list",
     "path": "userprofiles/{profileId}/projects",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "regions": {
   "methods": {
    "list": {
     "description": "Retrieves a list of regions.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.regions.list",
     "path": "userprofiles/{profileId}/regions",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "remarketingListShares": {
   "methods": {
    "get": {
     "description": "Gets one remarketing list share by remarketing list ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.remarketingListShares.get",
     "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing remarketing list share. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.remarketingListShares.patch",
     "path": "userprofiles/{profileId}/remarketingListShares",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing remarketing list share.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.remarketingListShares.update",
     "path": "userprofiles/{profileId}/remarketingListShares",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "remarketingLists": {
   "methods": {
    "get": {
     "description": "Gets one remarketing list by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.remarketingLists.get",
     "path": "userprofiles/{profileId}/remarketingLists/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new remarketing list.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.remarketingLists.insert",
     "path": "userprofiles/{profileId}/remarketingLists",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.remarketingLists.list",
     "path": "userprofiles/{profileId}/remarketingLists",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing remarketing list. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.remarketingLists.patch",
     "path": "userprofiles/{profileId}/remarketingLists",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing remarketing list.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.remarketingLists.update",
     "path": "userprofiles/{profileId}/remarketingLists",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "reports": {
   "methods": {
    "delete": {
     "description": "Deletes a report by its ID.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.reports.delete",
     "path": "userprofiles/{profileId}/reports/{reportId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Retrieves a report by its ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.reports.get",
     "path": "userprofiles/{profileId}/reports/{reportId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a report.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.reports.insert",
     "path": "userprofiles/{profileId}/reports",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves list of reports.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.reports.list",
     "path": "userprofiles/{profileId}/reports",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates a report. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.reports.patch",
     "path": "userprofiles/{profileId}/reports/{reportId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "run": {
     "description": "Runs a report.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.reports.run",
     "path": "userprofiles/{profileId}/reports/{reportId}/run",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a report.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.reports.update",
     "path": "userprofiles/{profileId}/reports/{reportId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "compatibleFields": {
     "methods": {
      "query": {
       "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "dfareporting.reports.compatibleFields.query",
       "path": "userprofiles/{profileId}/reports/compatiblefields/query",
       "scopes": [
        "https://www.googleapis.com/auth/dfareporting"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "files": {
     "methods": {
      "get": {
       "description": "Retrieves a report file. This method supports media download.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "dfareporting.reports.files.get",
       "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
       "scopes": [
        "https://www.googleapis.com/auth/dfareporting"
       ],
       "supportsMediaDownload": true,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists files for a report.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "dfareporting.reports.files.list",
       "path": "userprofiles/{profileId}/reports/{reportId}/files",
       "scopes": [
        "https://www.googleapis.com/auth/dfareporting"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "sites": {
   "methods": {
    "get": {
     "description": "Gets one site by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.sites.get",
     "path": "userprofiles/{profileId}/sites/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new site.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.sites.insert",
     "path": "userprofiles/{profileId}/sites",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.sites.list",
     "path": "userprofiles/{profileId}/sites",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing site. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.sites.patch",
     "path": "userprofiles/{profileId}/sites",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing site.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.sites.update",
     "path": "userprofiles/{profileId}/sites",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "sizes": {
   "methods": {
    "get": {
     "description": "Gets one size by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.sizes.get",
     "path": "userprofiles/{profileId}/sizes/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new size.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.sizes.insert",
     "path": "userprofiles/{profileId}/sizes",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of sizes, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.sizes.list",
     "path": "userprofiles/{profileId}/sizes",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "subaccounts": {
   "methods": {
    "get": {
     "description": "Gets one subaccount by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.subaccounts.get",
     "path": "userprofiles/{profileId}/subaccounts/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new subaccount.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.subaccounts.insert",
     "path": "userprofiles/{profileId}/subaccounts",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.subaccounts.list",
     "path": "userprofiles/{profileId}/subaccounts",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing subaccount. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.subaccounts.patch",
     "path": "userprofiles/{profileId}/subaccounts",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing subaccount.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.subaccounts.update",
     "path": "userprofiles/{profileId}/subaccounts",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "targetableRemarketingLists": {
   "methods": {
    "get": {
     "description": "Gets one remarketing list by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.targetableRemarketingLists.get",
     "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.targetableRemarketingLists.list",
     "path": "userprofiles/{profileId}/targetableRemarketingLists",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "targetingTemplates": {
   "methods": {
    "get": {
     "description": "Gets one targeting template by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.targetingTemplates.get",
     "path": "userprofiles/{profileId}/targetingTemplates/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new targeting template.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.targetingTemplates.insert",
     "path": "userprofiles/{profileId}/targetingTemplates",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.targetingTemplates.list",
     "path": "userprofiles/{profileId}/targetingTemplates",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing targeting template. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.targetingTemplates.patch",
     "path": "userprofiles/{profileId}/targetingTemplates",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing targeting template.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.targetingTemplates.update",
     "path": "userprofiles/{profileId}/targetingTemplates",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "userProfiles": {
   "methods": {
    "get": {
     "description": "Gets one user profile by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.userProfiles.get",
     "path": "userprofiles/{profileId}",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting",
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves list of user profiles for a user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.userProfiles.list",
     "path": "userprofiles",
     "scopes": [
      "https://www.googleapis.com/auth/dfareporting",
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "userRolePermissionGroups": {
   "methods": {
    "get": {
     "description": "Gets one user role permission group by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.userRolePermissionGroups.get",
     "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Gets a list of all supported user role permission groups.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.userRolePermissionGroups.list",
     "path": "userprofiles/{profileId}/userRolePermissionGroups",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "userRolePermissions": {
   "methods": {
    "get": {
     "description": "Gets one user role permission by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.userRolePermissions.get",
     "path": "userprofiles/{profileId}/userRolePermissions/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Gets a list of user role permissions, possibly filtered.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.userRolePermissions.list",
     "path": "userprofiles/{profileId}/userRolePermissions",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "userRoles": {
   "methods": {
    "delete": {
     "description": "Deletes an existing user role.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "dfareporting.userRoles.delete",
     "path": "userprofiles/{profileId}/userRoles/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets one user role by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.userRoles.get",
     "path": "userprofiles/{profileId}/userRoles/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new user role.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "dfareporting.userRoles.insert",
     "path": "userprofiles/{profileId}/userRoles",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.userRoles.list",
     "path": "userprofiles/{profileId}/userRoles",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates an existing user role. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "dfareporting.userRoles.patch",
     "path": "userprofiles/{profileId}/userRoles",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing user role.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "dfareporting.userRoles.update",
     "path": "userprofiles/{profileId}/userRoles",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "videoFormats": {
   "methods": {
    "get": {
     "description": "Gets one video format by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.videoFormats.get",
     "path": "userprofiles/{profileId}/videoFormats/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists available video formats.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "dfareporting.videoFormats.list",
     "path": "userprofiles/{profileId}/videoFormats",
     "scopes": [
      "https://www.googleapis.com/auth/dfatrafficking"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20170818",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "dfareporting/v2.8/",
 "title": "DCM/DFA Reporting And Trafficking API",
 "version": "v2.8",
 "version_module": null
}