{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/fitness.activity.read": {
     "description": "View your activity information in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.activity.write": {
     "description": "View and store your activity information in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.blood_glucose.read": {
     "description": "View blood glucose data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.blood_glucose.write": {
     "description": "View and store blood glucose data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.blood_pressure.read": {
     "description": "View blood pressure data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.blood_pressure.write": {
     "description": "View and store blood pressure data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.body.read": {
     "description": "View body sensor information in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.body.write": {
     "description": "View and store body sensor data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.body_temperature.read": {
     "description": "View body temperature data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.body_temperature.write": {
     "description": "View and store body temperature data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.location.read": {
     "description": "View your stored location data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.location.write": {
     "description": "View and store your location data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.nutrition.read": {
     "description": "View nutrition information in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.nutrition.write": {
     "description": "View and store nutrition information in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.oxygen_saturation.read": {
     "description": "View oxygen saturation data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.oxygen_saturation.write": {
     "description": "View and store oxygen saturation data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.reproductive_health.read": {
     "description": "View reproductive health data in Google Fit"
    },
    "https://www.googleapis.com/auth/fitness.reproductive_health.write": {
     "description": "View and store reproductive health data in Google Fit"
    }
   }
  }
 },
 "basePath": "/fitness/v1/users/",
 "baseUrl": "https://www.googleapis.com/fitness/v1/users/",
 "batchPath": "batch/fitness/v1",
 "canonicalName": null,
 "description": "Stores and accesses user data in the fitness store from apps on any platform.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/fit/rest/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/K1BxZmhfi_H1WlvW1SDsecgXAnE\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "fitness:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "fitness",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "users": {
   "methods": null,
   "resources": {
    "dataSources": {
     "methods": {
      "create": {
       "description": "Creates a new data source that is unique across all data sources belonging to this user. The data stream ID field can be omitted and will be generated by the server with the correct format. The data stream ID is an ordered combination of some fields from the data source. In addition to the data source fields reflected into the data source ID, the developer project number that is authenticated when creating the data source is included. This developer project number is obfus[...]",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "fitness.users.dataSources.create",
       "path": "{userId}/dataSources",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.write",
        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
        "https://www.googleapis.com/auth/fitness.body.write",
        "https://www.googleapis.com/auth/fitness.body_temperature.write",
        "https://www.googleapis.com/auth/fitness.location.write",
        "https://www.googleapis.com/auth/fitness.nutrition.write",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "delete": {
       "description": "Deletes the specified data source. The request will fail if the data source contains any data points.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "fitness.users.dataSources.delete",
       "path": "{userId}/dataSources/{dataSourceId}",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.write",
        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
        "https://www.googleapis.com/auth/fitness.body.write",
        "https://www.googleapis.com/auth/fitness.body_temperature.write",
        "https://www.googleapis.com/auth/fitness.location.write",
        "https://www.googleapis.com/auth/fitness.nutrition.write",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns the specified data source.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "fitness.users.dataSources.get",
       "path": "{userId}/dataSources/{dataSourceId}",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.read",
        "https://www.googleapis.com/auth/fitness.activity.write",
        "https://www.googleapis.com/auth/fitness.blood_glucose.read",
        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
        "https://www.googleapis.com/auth/fitness.blood_pressure.read",
        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
        "https://www.googleapis.com/auth/fitness.body.read",
        "https://www.googleapis.com/auth/fitness.body.write",
        "https://www.googleapis.com/auth/fitness.body_temperature.read",
        "https://www.googleapis.com/auth/fitness.body_temperature.write",
        "https://www.googleapis.com/auth/fitness.location.read",
        "https://www.googleapis.com/auth/fitness.location.write",
        "https://www.googleapis.com/auth/fitness.nutrition.read",
        "https://www.googleapis.com/auth/fitness.nutrition.write",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
        "https://www.googleapis.com/auth/fitness.reproductive_health.read",
        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists all data sources that are visible to the developer, using the OAuth scopes provided. The list is not exhaustive; the user may have private data sources that are only visible to other developers, or calls using other scopes.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "fitness.users.dataSources.list",
       "path": "{userId}/dataSources",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.read",
        "https://www.googleapis.com/auth/fitness.activity.write",
        "https://www.googleapis.com/auth/fitness.blood_glucose.read",
        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
        "https://www.googleapis.com/auth/fitness.blood_pressure.read",
        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
        "https://www.googleapis.com/auth/fitness.body.read",
        "https://www.googleapis.com/auth/fitness.body.write",
        "https://www.googleapis.com/auth/fitness.body_temperature.read",
        "https://www.googleapis.com/auth/fitness.body_temperature.write",
        "https://www.googleapis.com/auth/fitness.location.read",
        "https://www.googleapis.com/auth/fitness.location.write",
        "https://www.googleapis.com/auth/fitness.nutrition.read",
        "https://www.googleapis.com/auth/fitness.nutrition.write",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
        "https://www.googleapis.com/auth/fitness.reproductive_health.read",
        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified.\n\nData sources are identified by their dataStreamId. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "fitness.users.dataSources.patch",
       "path": "{userId}/dataSources/{dataSourceId}",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.write",
        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
        "https://www.googleapis.com/auth/fitness.body.write",
        "https://www.googleapis.com/auth/fitness.body_temperature.write",
        "https://www.googleapis.com/auth/fitness.location.write",
        "https://www.googleapis.com/auth/fitness.nutrition.write",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified.\n\nData sources are identified by their dataStreamId.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "fitness.users.dataSources.update",
       "path": "{userId}/dataSources/{dataSourceId}",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.write",
        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
        "https://www.googleapis.com/auth/fitness.body.write",
        "https://www.googleapis.com/auth/fitness.body_temperature.write",
        "https://www.googleapis.com/auth/fitness.location.write",
        "https://www.googleapis.com/auth/fitness.nutrition.write",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": {
      "dataPointChanges": {
       "methods": {
        "list": {
         "description": "Queries for user's data point changes for a particular data source.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "fitness.users.dataSources.dataPointChanges.list",
         "path": "{userId}/dataSources/{dataSourceId}/dataPointChanges",
         "scopes": [
          "https://www.googleapis.com/auth/fitness.activity.read",
          "https://www.googleapis.com/auth/fitness.activity.write",
          "https://www.googleapis.com/auth/fitness.blood_glucose.read",
          "https://www.googleapis.com/auth/fitness.blood_glucose.write",
          "https://www.googleapis.com/auth/fitness.blood_pressure.read",
          "https://www.googleapis.com/auth/fitness.blood_pressure.write",
          "https://www.googleapis.com/auth/fitness.body.read",
          "https://www.googleapis.com/auth/fitness.body.write",
          "https://www.googleapis.com/auth/fitness.body_temperature.read",
          "https://www.googleapis.com/auth/fitness.body_temperature.write",
          "https://www.googleapis.com/auth/fitness.location.read",
          "https://www.googleapis.com/auth/fitness.location.write",
          "https://www.googleapis.com/auth/fitness.nutrition.read",
          "https://www.googleapis.com/auth/fitness.nutrition.write",
          "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
          "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
          "https://www.googleapis.com/auth/fitness.reproductive_health.read",
          "https://www.googleapis.com/auth/fitness.reproductive_health.write"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "datasets": {
       "methods": {
        "delete": {
         "description": "Performs an inclusive delete of all data points whose start and end times have any overlap with the time range specified by the dataset ID. For most data types, the entire data point will be deleted. For data types where the time span represents a consistent value (such as com.google.activity.segment), and a data point straddles either end point of the dataset, only the overlapping portion of the data point will be deleted.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "fitness.users.dataSources.datasets.delete",
         "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
         "scopes": [
          "https://www.googleapis.com/auth/fitness.activity.write",
          "https://www.googleapis.com/auth/fitness.blood_glucose.write",
          "https://www.googleapis.com/auth/fitness.blood_pressure.write",
          "https://www.googleapis.com/auth/fitness.body.write",
          "https://www.googleapis.com/auth/fitness.body_temperature.write",
          "https://www.googleapis.com/auth/fitness.location.write",
          "https://www.googleapis.com/auth/fitness.nutrition.write",
          "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
          "https://www.googleapis.com/auth/fitness.reproductive_health.write"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Returns a dataset containing all data points whose start and end times overlap with the specified range of the dataset minimum start time and maximum end time. Specifically, any data point whose start time is less than or equal to the dataset end time and whose end time is greater than or equal to the dataset start time.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "fitness.users.dataSources.datasets.get",
         "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
         "scopes": [
          "https://www.googleapis.com/auth/fitness.activity.read",
          "https://www.googleapis.com/auth/fitness.activity.write",
          "https://www.googleapis.com/auth/fitness.blood_glucose.read",
          "https://www.googleapis.com/auth/fitness.blood_glucose.write",
          "https://www.googleapis.com/auth/fitness.blood_pressure.read",
          "https://www.googleapis.com/auth/fitness.blood_pressure.write",
          "https://www.googleapis.com/auth/fitness.body.read",
          "https://www.googleapis.com/auth/fitness.body.write",
          "https://www.googleapis.com/auth/fitness.body_temperature.read",
          "https://www.googleapis.com/auth/fitness.body_temperature.write",
          "https://www.googleapis.com/auth/fitness.location.read",
          "https://www.googleapis.com/auth/fitness.location.write",
          "https://www.googleapis.com/auth/fitness.nutrition.read",
          "https://www.googleapis.com/auth/fitness.nutrition.write",
          "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
          "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
          "https://www.googleapis.com/auth/fitness.reproductive_health.read",
          "https://www.googleapis.com/auth/fitness.reproductive_health.write"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "patch": {
         "description": "Adds data points to a dataset. The dataset need not be previously created. All points within the given dataset will be returned with subsquent calls to retrieve this dataset. Data points can belong to more than one dataset. This method does not use patch semantics.",
         "etagRequired": null,
         "httpMethod": "PATCH",
         "id": "fitness.users.dataSources.datasets.patch",
         "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
         "scopes": [
          "https://www.googleapis.com/auth/fitness.activity.write",
          "https://www.googleapis.com/auth/fitness.blood_glucose.write",
          "https://www.googleapis.com/auth/fitness.blood_pressure.write",
          "https://www.googleapis.com/auth/fitness.body.write",
          "https://www.googleapis.com/auth/fitness.body_temperature.write",
          "https://www.googleapis.com/auth/fitness.location.write",
          "https://www.googleapis.com/auth/fitness.nutrition.write",
          "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
          "https://www.googleapis.com/auth/fitness.reproductive_health.write"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      }
     },
     "ETag": null
    },
    "dataset": {
     "methods": {
      "aggregate": {
       "description": "Aggregates data of a certain type or stream into buckets divided by a given type of boundary. Multiple data sets of multiple types and from multiple sources can be aggreated into exactly one bucket type per request.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "fitness.users.dataset.aggregate",
       "path": "{userId}/dataset:aggregate",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.read",
        "https://www.googleapis.com/auth/fitness.activity.write",
        "https://www.googleapis.com/auth/fitness.blood_glucose.read",
        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
        "https://www.googleapis.com/auth/fitness.blood_pressure.read",
        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
        "https://www.googleapis.com/auth/fitness.body.read",
        "https://www.googleapis.com/auth/fitness.body.write",
        "https://www.googleapis.com/auth/fitness.body_temperature.read",
        "https://www.googleapis.com/auth/fitness.body_temperature.write",
        "https://www.googleapis.com/auth/fitness.location.read",
        "https://www.googleapis.com/auth/fitness.location.write",
        "https://www.googleapis.com/auth/fitness.nutrition.read",
        "https://www.googleapis.com/auth/fitness.nutrition.write",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
        "https://www.googleapis.com/auth/fitness.reproductive_health.read",
        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "sessions": {
     "methods": {
      "delete": {
       "description": "Deletes a session specified by the given session ID.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "fitness.users.sessions.delete",
       "path": "{userId}/sessions/{sessionId}",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists sessions previously created.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "fitness.users.sessions.list",
       "path": "{userId}/sessions",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.read",
        "https://www.googleapis.com/auth/fitness.activity.write",
        "https://www.googleapis.com/auth/fitness.blood_glucose.read",
        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
        "https://www.googleapis.com/auth/fitness.blood_pressure.read",
        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
        "https://www.googleapis.com/auth/fitness.body.read",
        "https://www.googleapis.com/auth/fitness.body.write",
        "https://www.googleapis.com/auth/fitness.body_temperature.read",
        "https://www.googleapis.com/auth/fitness.body_temperature.write",
        "https://www.googleapis.com/auth/fitness.location.read",
        "https://www.googleapis.com/auth/fitness.location.write",
        "https://www.googleapis.com/auth/fitness.nutrition.read",
        "https://www.googleapis.com/auth/fitness.nutrition.write",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
        "https://www.googleapis.com/auth/fitness.reproductive_health.read",
        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates or insert a given session.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "fitness.users.sessions.update",
       "path": "{userId}/sessions/{sessionId}",
       "scopes": [
        "https://www.googleapis.com/auth/fitness.activity.write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20170922",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "fitness/v1/users/",
 "title": "Fitness",
 "version": "v1",
 "version_module": null
}