{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://mail.google.com/": {
     "description": "Read, send, delete, and manage your email"
    },
    "https://www.googleapis.com/auth/gmail.compose": {
     "description": "Manage drafts and send emails"
    },
    "https://www.googleapis.com/auth/gmail.insert": {
     "description": "Insert mail into your mailbox"
    },
    "https://www.googleapis.com/auth/gmail.labels": {
     "description": "Manage mailbox labels"
    },
    "https://www.googleapis.com/auth/gmail.metadata": {
     "description": "View your email message metadata such as labels and headers, but not the email body"
    },
    "https://www.googleapis.com/auth/gmail.modify": {
     "description": "View and modify but not delete your email"
    },
    "https://www.googleapis.com/auth/gmail.readonly": {
     "description": "View your email messages and settings"
    },
    "https://www.googleapis.com/auth/gmail.send": {
     "description": "Send email on your behalf"
    },
    "https://www.googleapis.com/auth/gmail.settings.basic": {
     "description": "Manage your basic mail settings"
    },
    "https://www.googleapis.com/auth/gmail.settings.sharing": {
     "description": "Manage your sensitive mail settings, including who can manage your mail"
    }
   }
  }
 },
 "basePath": "/gmail/v1/users/",
 "baseUrl": "https://www.googleapis.com/gmail/v1/users/",
 "batchPath": "batch/gmail/v1",
 "canonicalName": null,
 "description": "Access Gmail mailboxes including sending user email.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/gmail/api/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/Jxtw49Vdy6XkRjNk3GQgsLTd4CA\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "gmail:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "gmail",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "users": {
   "methods": {
    "getProfile": {
     "description": "Gets the current user's Gmail profile.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "gmail.users.getProfile",
     "path": "{userId}/profile",
     "scopes": [
      "https://mail.google.com/",
      "https://www.googleapis.com/auth/gmail.compose",
      "https://www.googleapis.com/auth/gmail.metadata",
      "https://www.googleapis.com/auth/gmail.modify",
      "https://www.googleapis.com/auth/gmail.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "stop": {
     "description": "Stop receiving push notifications for the given user mailbox.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "gmail.users.stop",
     "path": "{userId}/stop",
     "scopes": [
      "https://mail.google.com/",
      "https://www.googleapis.com/auth/gmail.metadata",
      "https://www.googleapis.com/auth/gmail.modify",
      "https://www.googleapis.com/auth/gmail.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "watch": {
     "description": "Set up or update a push notification watch on the given user mailbox.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "gmail.users.watch",
     "path": "{userId}/watch",
     "scopes": [
      "https://mail.google.com/",
      "https://www.googleapis.com/auth/gmail.metadata",
      "https://www.googleapis.com/auth/gmail.modify",
      "https://www.googleapis.com/auth/gmail.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "drafts": {
     "methods": {
      "create": {
       "description": "Creates a new draft with the DRAFT label.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.drafts.create",
       "path": "{userId}/drafts",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": true,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "delete": {
       "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "gmail.users.drafts.delete",
       "path": "{userId}/drafts/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets the specified draft.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.drafts.get",
       "path": "{userId}/drafts/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists the drafts in the user's mailbox.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.drafts.list",
       "path": "{userId}/drafts",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "send": {
       "description": "Sends the specified, existing draft to the recipients in the To, Cc, and Bcc headers.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.drafts.send",
       "path": "{userId}/drafts/send",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": true,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Replaces a draft's content.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "gmail.users.drafts.update",
       "path": "{userId}/drafts/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": true,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "history": {
     "methods": {
      "list": {
       "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing historyId).",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.history.list",
       "path": "{userId}/history",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.metadata",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "labels": {
     "methods": {
      "create": {
       "description": "Creates a new label.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.labels.create",
       "path": "{userId}/labels",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.labels",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "delete": {
       "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "gmail.users.labels.delete",
       "path": "{userId}/labels/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.labels",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets the specified label.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.labels.get",
       "path": "{userId}/labels/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.labels",
        "https://www.googleapis.com/auth/gmail.metadata",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists all labels in the user's mailbox.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.labels.list",
       "path": "{userId}/labels",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.labels",
        "https://www.googleapis.com/auth/gmail.metadata",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "patch": {
       "description": "Updates the specified label. This method supports patch semantics.",
       "etagRequired": null,
       "httpMethod": "PATCH",
       "id": "gmail.users.labels.patch",
       "path": "{userId}/labels/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.labels",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates the specified label.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "gmail.users.labels.update",
       "path": "{userId}/labels/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.labels",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "messages": {
     "methods": {
      "batchDelete": {
       "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.messages.batchDelete",
       "path": "{userId}/messages/batchDelete",
       "scopes": [
        "https://mail.google.com/"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "batchModify": {
       "description": "Modifies the labels on the specified messages.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.messages.batchModify",
       "path": "{userId}/messages/batchModify",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "delete": {
       "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer messages.trash instead.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "gmail.users.messages.delete",
       "path": "{userId}/messages/{id}",
       "scopes": [
        "https://mail.google.com/"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets the specified message.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.messages.get",
       "path": "{userId}/messages/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.metadata",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "import": {
       "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. Does not send a message.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.messages.import",
       "path": "{userId}/messages/import",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.insert",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": true,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Directly inserts a message into only this user's mailbox similar to IMAP APPEND, bypassing most scanning and classification. Does not send a message.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.messages.insert",
       "path": "{userId}/messages",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.insert",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": true,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists the messages in the user's mailbox.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.messages.list",
       "path": "{userId}/messages",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.metadata",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "modify": {
       "description": "Modifies the labels on the specified message.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.messages.modify",
       "path": "{userId}/messages/{id}/modify",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "send": {
       "description": "Sends the specified message to the recipients in the To, Cc, and Bcc headers.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.messages.send",
       "path": "{userId}/messages/send",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.compose",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.send"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": true,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "trash": {
       "description": "Moves the specified message to the trash.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.messages.trash",
       "path": "{userId}/messages/{id}/trash",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "untrash": {
       "description": "Removes the specified message from the trash.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.messages.untrash",
       "path": "{userId}/messages/{id}/untrash",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": {
      "attachments": {
       "methods": {
        "get": {
         "description": "Gets the specified message attachment.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "gmail.users.messages.attachments.get",
         "path": "{userId}/messages/{messageId}/attachments/{id}",
         "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      }
     },
     "ETag": null
    },
    "settings": {
     "methods": {
      "getAutoForwarding": {
       "description": "Gets the auto-forwarding setting for the specified account.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.settings.getAutoForwarding",
       "path": "{userId}/settings/autoForwarding",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.settings.basic"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "getImap": {
       "description": "Gets IMAP settings.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.settings.getImap",
       "path": "{userId}/settings/imap",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.settings.basic"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "getPop": {
       "description": "Gets POP settings.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.settings.getPop",
       "path": "{userId}/settings/pop",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.settings.basic"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "getVacation": {
       "description": "Gets vacation responder settings.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.settings.getVacation",
       "path": "{userId}/settings/vacation",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.settings.basic"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "updateAutoForwarding": {
       "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "gmail.users.settings.updateAutoForwarding",
       "path": "{userId}/settings/autoForwarding",
       "scopes": [
        "https://www.googleapis.com/auth/gmail.settings.sharing"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "updateImap": {
       "description": "Updates IMAP settings.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "gmail.users.settings.updateImap",
       "path": "{userId}/settings/imap",
       "scopes": [
        "https://www.googleapis.com/auth/gmail.settings.basic"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "updatePop": {
       "description": "Updates POP settings.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "gmail.users.settings.updatePop",
       "path": "{userId}/settings/pop",
       "scopes": [
        "https://www.googleapis.com/auth/gmail.settings.basic"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "updateVacation": {
       "description": "Updates vacation responder settings.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "gmail.users.settings.updateVacation",
       "path": "{userId}/settings/vacation",
       "scopes": [
        "https://www.googleapis.com/auth/gmail.settings.basic"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": {
      "filters": {
       "methods": {
        "create": {
         "description": "Creates a filter.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "gmail.users.settings.filters.create",
         "path": "{userId}/settings/filters",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.basic"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes a filter.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "gmail.users.settings.filters.delete",
         "path": "{userId}/settings/filters/{id}",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.basic"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets a filter.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "gmail.users.settings.filters.get",
         "path": "{userId}/settings/filters/{id}",
         "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.settings.basic"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists the message filters of a Gmail user.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "gmail.users.settings.filters.list",
         "path": "{userId}/settings/filters",
         "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.settings.basic"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "forwardingAddresses": {
       "methods": {
        "create": {
         "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to pending; otherwise, the resource will be created with verification status set to accepted.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "gmail.users.settings.forwardingAddresses.create",
         "path": "{userId}/settings/forwardingAddresses",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.sharing"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes the specified forwarding address and revokes any verification that may have been required.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "gmail.users.settings.forwardingAddresses.delete",
         "path": "{userId}/settings/forwardingAddresses/{forwardingEmail}",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.sharing"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets the specified forwarding address.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "gmail.users.settings.forwardingAddresses.get",
         "path": "{userId}/settings/forwardingAddresses/{forwardingEmail}",
         "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.settings.basic"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists the forwarding addresses for the specified account.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "gmail.users.settings.forwardingAddresses.list",
         "path": "{userId}/settings/forwardingAddresses",
         "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.settings.basic"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "sendAs": {
       "methods": {
        "create": {
         "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to pending; otherwise, the resource will be created with verification status set to accepted. If a signature is provided, Gmail will sanitize the HTML[...]",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "gmail.users.settings.sendAs.create",
         "path": "{userId}/settings/sendAs",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.sharing"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "gmail.users.settings.sendAs.delete",
         "path": "{userId}/settings/sendAs/{sendAsEmail}",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.sharing"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "gmail.users.settings.sendAs.get",
         "path": "{userId}/settings/sendAs/{sendAsEmail}",
         "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.settings.basic"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "gmail.users.settings.sendAs.list",
         "path": "{userId}/settings/sendAs",
         "scopes": [
          "https://mail.google.com/",
          "https://www.googleapis.com/auth/gmail.modify",
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.settings.basic"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "patch": {
         "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias.\n\nAddresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority. This method supports patch semantics.",
         "etagRequired": null,
         "httpMethod": "PATCH",
         "id": "gmail.users.settings.sendAs.patch",
         "path": "{userId}/settings/sendAs/{sendAsEmail}",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.basic",
          "https://www.googleapis.com/auth/gmail.settings.sharing"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "update": {
         "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias.\n\nAddresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "gmail.users.settings.sendAs.update",
         "path": "{userId}/settings/sendAs/{sendAsEmail}",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.basic",
          "https://www.googleapis.com/auth/gmail.settings.sharing"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "verify": {
         "description": "Sends a verification email to the specified send-as alias address. The verification status must be pending.\n\nThis method is only available to service account clients that have been delegated domain-wide authority.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "gmail.users.settings.sendAs.verify",
         "path": "{userId}/settings/sendAs/{sendAsEmail}/verify",
         "scopes": [
          "https://www.googleapis.com/auth/gmail.settings.sharing"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": {
        "smimeInfo": {
         "methods": {
          "delete": {
           "description": "Deletes the specified S/MIME config for the specified send-as alias.",
           "etagRequired": null,
           "httpMethod": "DELETE",
           "id": "gmail.users.settings.sendAs.smimeInfo.delete",
           "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
           "scopes": [
            "https://www.googleapis.com/auth/gmail.settings.basic",
            "https://www.googleapis.com/auth/gmail.settings.sharing"
           ],
           "supportsMediaDownload": null,
           "supportsMediaUpload": null,
           "supportsSubscription": null,
           "useMediaDownloadService": null,
           "ETag": null
          },
          "get": {
           "description": "Gets the specified S/MIME config for the specified send-as alias.",
           "etagRequired": null,
           "httpMethod": "GET",
           "id": "gmail.users.settings.sendAs.smimeInfo.get",
           "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
           "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly",
            "https://www.googleapis.com/auth/gmail.settings.basic",
            "https://www.googleapis.com/auth/gmail.settings.sharing"
           ],
           "supportsMediaDownload": null,
           "supportsMediaUpload": null,
           "supportsSubscription": null,
           "useMediaDownloadService": null,
           "ETag": null
          },
          "insert": {
           "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.",
           "etagRequired": null,
           "httpMethod": "POST",
           "id": "gmail.users.settings.sendAs.smimeInfo.insert",
           "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
           "scopes": [
            "https://www.googleapis.com/auth/gmail.settings.basic",
            "https://www.googleapis.com/auth/gmail.settings.sharing"
           ],
           "supportsMediaDownload": null,
           "supportsMediaUpload": null,
           "supportsSubscription": null,
           "useMediaDownloadService": null,
           "ETag": null
          },
          "list": {
           "description": "Lists S/MIME configs for the specified send-as alias.",
           "etagRequired": null,
           "httpMethod": "GET",
           "id": "gmail.users.settings.sendAs.smimeInfo.list",
           "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
           "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly",
            "https://www.googleapis.com/auth/gmail.settings.basic",
            "https://www.googleapis.com/auth/gmail.settings.sharing"
           ],
           "supportsMediaDownload": null,
           "supportsMediaUpload": null,
           "supportsSubscription": null,
           "useMediaDownloadService": null,
           "ETag": null
          },
          "setDefault": {
           "description": "Sets the default S/MIME config for the specified send-as alias.",
           "etagRequired": null,
           "httpMethod": "POST",
           "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
           "path": "{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
           "scopes": [
            "https://www.googleapis.com/auth/gmail.settings.basic",
            "https://www.googleapis.com/auth/gmail.settings.sharing"
           ],
           "supportsMediaDownload": null,
           "supportsMediaUpload": null,
           "supportsSubscription": null,
           "useMediaDownloadService": null,
           "ETag": null
          }
         },
         "resources": null,
         "ETag": null
        }
       },
       "ETag": null
      }
     },
     "ETag": null
    },
    "threads": {
     "methods": {
      "delete": {
       "description": "Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer threads.trash instead.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "gmail.users.threads.delete",
       "path": "{userId}/threads/{id}",
       "scopes": [
        "https://mail.google.com/"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets the specified thread.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.threads.get",
       "path": "{userId}/threads/{id}",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.metadata",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists the threads in the user's mailbox.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "gmail.users.threads.list",
       "path": "{userId}/threads",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.metadata",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/gmail.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "modify": {
       "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.threads.modify",
       "path": "{userId}/threads/{id}/modify",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "trash": {
       "description": "Moves the specified thread to the trash.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.threads.trash",
       "path": "{userId}/threads/{id}/trash",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "untrash": {
       "description": "Removes the specified thread from the trash.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "gmail.users.threads.untrash",
       "path": "{userId}/threads/{id}/untrash",
       "scopes": [
        "https://mail.google.com/",
        "https://www.googleapis.com/auth/gmail.modify"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20170926",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "gmail/v1/users/",
 "title": "Gmail API",
 "version": "v1",
 "version_module": null
}