{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/glass.location": {
     "description": "View your location"
    },
    "https://www.googleapis.com/auth/glass.timeline": {
     "description": "View and manage your Glass timeline"
    }
   }
  }
 },
 "basePath": "/mirror/v1/",
 "baseUrl": "https://www.googleapis.com/mirror/v1/",
 "batchPath": "batch/mirror/v1",
 "canonicalName": null,
 "description": "Interacts with Glass users via the timeline.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/glass",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/WPRVY9WdjtlhnPeIWQ7gxByfU3U\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "mirror:v1",
 "kind": "discovery#restDescription",
 "labels": [
  "limited_availability"
 ],
 "methods": null,
 "name": "mirror",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "accounts": {
   "methods": {
    "insert": {
     "description": "Inserts a new account for a user",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "mirror.accounts.insert",
     "path": "accounts/{userToken}/{accountType}/{accountName}",
     "scopes": null,
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "contacts": {
   "methods": {
    "delete": {
     "description": "Deletes a contact.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "mirror.contacts.delete",
     "path": "contacts/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets a single contact by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "mirror.contacts.get",
     "path": "contacts/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new contact.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "mirror.contacts.insert",
     "path": "contacts",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of contacts for the authenticated user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "mirror.contacts.list",
     "path": "contacts",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates a contact in place. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "mirror.contacts.patch",
     "path": "contacts/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a contact in place.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "mirror.contacts.update",
     "path": "contacts/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "locations": {
   "methods": {
    "get": {
     "description": "Gets a single location by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "mirror.locations.get",
     "path": "locations/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of locations for the user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "mirror.locations.list",
     "path": "locations",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "settings": {
   "methods": {
    "get": {
     "description": "Gets a single setting by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "mirror.settings.get",
     "path": "settings/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "subscriptions": {
   "methods": {
    "delete": {
     "description": "Deletes a subscription.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "mirror.subscriptions.delete",
     "path": "subscriptions/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a new subscription.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "mirror.subscriptions.insert",
     "path": "subscriptions",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of subscriptions for the authenticated user and service.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "mirror.subscriptions.list",
     "path": "subscriptions",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates an existing subscription in place.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "mirror.subscriptions.update",
     "path": "subscriptions/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "timeline": {
   "methods": {
    "delete": {
     "description": "Deletes a timeline item.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "mirror.timeline.delete",
     "path": "timeline/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets a single timeline item by ID.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "mirror.timeline.get",
     "path": "timeline/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new item into the timeline.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "mirror.timeline.insert",
     "path": "timeline",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Retrieves a list of timeline items for the authenticated user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "mirror.timeline.list",
     "path": "timeline",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates a timeline item in place. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "mirror.timeline.patch",
     "path": "timeline/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a timeline item in place.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "mirror.timeline.update",
     "path": "timeline/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/glass.location",
      "https://www.googleapis.com/auth/glass.timeline"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "attachments": {
     "methods": {
      "delete": {
       "description": "Deletes an attachment from a timeline item.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "mirror.timeline.attachments.delete",
       "path": "timeline/{itemId}/attachments/{attachmentId}",
       "scopes": [
        "https://www.googleapis.com/auth/glass.timeline"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Retrieves an attachment on a timeline item by item ID and attachment ID.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "mirror.timeline.attachments.get",
       "path": "timeline/{itemId}/attachments/{attachmentId}",
       "scopes": [
        "https://www.googleapis.com/auth/glass.timeline"
       ],
       "supportsMediaDownload": true,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "insert": {
       "description": "Adds a new attachment to a timeline item.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "mirror.timeline.attachments.insert",
       "path": "timeline/{itemId}/attachments",
       "scopes": [
        "https://www.googleapis.com/auth/glass.timeline"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": true,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Returns a list of attachments for a timeline item.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "mirror.timeline.attachments.list",
       "path": "timeline/{itemId}/attachments",
       "scopes": [
        "https://www.googleapis.com/auth/glass.timeline"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20170419",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "mirror/v1/",
 "title": "Google Mirror API",
 "version": "v1",
 "version_module": null
}