{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/plus.login": {
     "description": "Know the list of people in your circles, your age range, and language"
    },
    "https://www.googleapis.com/auth/userinfo.profile": {
     "description": "View your basic profile info"
    },
    "https://www.googleapis.com/auth/user.addresses.read": {
     "description": "View your street addresses"
    },
    "https://www.googleapis.com/auth/contacts": {
     "description": "Manage your contacts"
    },
    "https://www.googleapis.com/auth/user.emails.read": {
     "description": "View your email addresses"
    },
    "https://www.googleapis.com/auth/user.phonenumbers.read": {
     "description": "View your phone numbers"
    },
    "https://www.googleapis.com/auth/userinfo.email": {
     "description": "View your email address"
    },
    "https://www.googleapis.com/auth/contacts.readonly": {
     "description": "View your contacts"
    },
    "https://www.googleapis.com/auth/user.birthday.read": {
     "description": "View your complete date of birth"
    }
   }
  }
 },
 "basePath": "",
 "baseUrl": "https://people.googleapis.com/",
 "batchPath": "batch",
 "canonicalName": "People Service",
 "description": "Provides access to information about profiles and contacts.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/people/",
 "etag": null,
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "people:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "people",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "people": {
   "methods": {
    "updateContact": {
     "description": "Update contact data for an existing contact person. Any non-contact data\nwill not be modified.\n\nThe request throws a 400 error if `updatePersonFields` is not specified.\n<br>\nThe request throws a 400 error if `person.metadata.sources` is not\nspecified for the contact to be updated.\n<br>\nThe request throws a 412 error if `person.metadata.sources.etag` is\ndifferent than the contact's etag, which indicates the contact has changed\nsince its data was read. Clients should[...]",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "people.people.updateContact",
     "path": "v1/{+resourceName}:updateContact",
     "scopes": [
      "https://www.googleapis.com/auth/contacts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "createContact": {
     "description": "Create a new contact and return the person resource for that contact.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "people.people.createContact",
     "path": "v1/people:createContact",
     "scopes": [
      "https://www.googleapis.com/auth/contacts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "deleteContact": {
     "description": "Delete a contact person. Any non-contact data will not be deleted.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "people.people.deleteContact",
     "path": "v1/{+resourceName}:deleteContact",
     "scopes": [
      "https://www.googleapis.com/auth/contacts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getBatchGet": {
     "description": "Provides information about a list of specific people by specifying a list\nof requested resource names. Use `people/me` to indicate the authenticated\nuser.\n<br>\nThe request throws a 400 error if 'personFields' is not specified.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "people.people.getBatchGet",
     "path": "v1/people:batchGet",
     "scopes": [
      "https://www.googleapis.com/auth/contacts",
      "https://www.googleapis.com/auth/contacts.readonly",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/user.addresses.read",
      "https://www.googleapis.com/auth/user.birthday.read",
      "https://www.googleapis.com/auth/user.emails.read",
      "https://www.googleapis.com/auth/user.phonenumbers.read",
      "https://www.googleapis.com/auth/userinfo.email",
      "https://www.googleapis.com/auth/userinfo.profile"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Provides information about a person by specifying a resource name. Use\n`people/me` to indicate the authenticated user.\n<br>\nThe request throws a 400 error if 'personFields' is not specified.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "people.people.get",
     "path": "v1/{+resourceName}",
     "scopes": [
      "https://www.googleapis.com/auth/contacts",
      "https://www.googleapis.com/auth/contacts.readonly",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/user.addresses.read",
      "https://www.googleapis.com/auth/user.birthday.read",
      "https://www.googleapis.com/auth/user.emails.read",
      "https://www.googleapis.com/auth/user.phonenumbers.read",
      "https://www.googleapis.com/auth/userinfo.email",
      "https://www.googleapis.com/auth/userinfo.profile"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "connections": {
     "methods": {
      "list": {
       "description": "Provides a list of the authenticated user's contacts merged with any\nconnected profiles.\n<br>\nThe request throws a 400 error if 'personFields' is not specified.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "people.people.connections.list",
       "path": "v1/{+resourceName}/connections",
       "scopes": [
        "https://www.googleapis.com/auth/contacts",
        "https://www.googleapis.com/auth/contacts.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "contactGroups": {
   "methods": {
    "get": {
     "description": "Get a specific contact group owned by the authenticated user by specifying\na contact group resource name.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "people.contactGroups.get",
     "path": "v1/{+resourceName}",
     "scopes": [
      "https://www.googleapis.com/auth/contacts",
      "https://www.googleapis.com/auth/contacts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update the name of an existing contact group owned by the authenticated\nuser.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "people.contactGroups.update",
     "path": "v1/{+resourceName}",
     "scopes": [
      "https://www.googleapis.com/auth/contacts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "batchGet": {
     "description": "Get a list of contact groups owned by the authenticated user by specifying\na list of contact group resource names.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "people.contactGroups.batchGet",
     "path": "v1/contactGroups:batchGet",
     "scopes": [
      "https://www.googleapis.com/auth/contacts",
      "https://www.googleapis.com/auth/contacts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Delete an existing contact group owned by the authenticated user by\nspecifying a contact group resource name.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "people.contactGroups.delete",
     "path": "v1/{+resourceName}",
     "scopes": [
      "https://www.googleapis.com/auth/contacts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List all contact groups owned by the authenticated user. Members of the\ncontact groups are not populated.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "people.contactGroups.list",
     "path": "v1/contactGroups",
     "scopes": [
      "https://www.googleapis.com/auth/contacts",
      "https://www.googleapis.com/auth/contacts.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "create": {
     "description": "Create a new contact group owned by the authenticated user.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "people.contactGroups.create",
     "path": "v1/contactGroups",
     "scopes": [
      "https://www.googleapis.com/auth/contacts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "members": {
     "methods": {
      "modify": {
       "description": "Modify the members of a contact group owned by the authenticated user.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "people.contactGroups.members.modify",
       "path": "v1/{+resourceName}/members:modify",
       "scopes": [
        "https://www.googleapis.com/auth/contacts"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20171005",
 "rootUrl": "https://people.googleapis.com/",
 "servicePath": "",
 "title": "Google People API",
 "version": "v1",
 "version_module": true
}