{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/plus.circles.read": {
     "description": "View your circles and the people and pages in them"
    },
    "https://www.googleapis.com/auth/plus.circles.write": {
     "description": "Manage your circles and add people and pages. People and pages you add to your circles will be notified. Others may see this information publicly. People you add to circles can use Hangouts with you."
    },
    "https://www.googleapis.com/auth/plus.login": {
     "description": "Know the list of people in your circles, your age range, and language"
    },
    "https://www.googleapis.com/auth/plus.me": {
     "description": "Know who you are on Google"
    },
    "https://www.googleapis.com/auth/plus.media.upload": {
     "description": "Send your photos and videos to Google+"
    },
    "https://www.googleapis.com/auth/plus.profiles.read": {
     "description": "View your own Google+ profile and profiles visible to you"
    },
    "https://www.googleapis.com/auth/plus.stream.read": {
     "description": "View your Google+ posts, comments, and stream"
    },
    "https://www.googleapis.com/auth/plus.stream.write": {
     "description": "Manage your Google+ posts, comments, and stream"
    },
    "https://www.googleapis.com/auth/userinfo.email": {
     "description": "View your email address"
    },
    "https://www.googleapis.com/auth/userinfo.profile": {
     "description": "View your basic profile info"
    }
   }
  }
 },
 "basePath": "/plusDomains/v1/",
 "baseUrl": "https://www.googleapis.com/plusDomains/v1/",
 "batchPath": "batch",
 "canonicalName": null,
 "description": "Builds on top of the Google+ platform for Google Apps Domains.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/+/domains/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/mgTNhRz8BUIUTZvlG4NGzgfWt2o\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "plusDomains:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "plusDomains",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "activities": {
   "methods": {
    "get": {
     "description": "Get an activity.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.activities.get",
     "path": "activities/{activityId}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.stream.read"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Create a new activity for the authenticated user.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "plusDomains.activities.insert",
     "path": "people/{userId}/activities",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.stream.write"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List all of the activities in the specified collection for a particular user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.activities.list",
     "path": "people/{userId}/activities/{collection}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.stream.read"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "audiences": {
   "methods": {
    "list": {
     "description": "List all of the audiences to which a user can share.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.audiences.list",
     "path": "people/{userId}/audiences",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "circles": {
   "methods": {
    "addPeople": {
     "description": "Add a person to a circle. Google+ limits certain circle operations, including the number of circle adds. Learn More.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "plusDomains.circles.addPeople",
     "path": "circles/{circleId}/people",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Get a circle.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.circles.get",
     "path": "circles/{circleId}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Create a new circle for the authenticated user.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "plusDomains.circles.insert",
     "path": "people/{userId}/circles",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List all of the circles for a user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.circles.list",
     "path": "people/{userId}/circles",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Update a circle's description. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "plusDomains.circles.patch",
     "path": "circles/{circleId}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "remove": {
     "description": "Delete a circle.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "plusDomains.circles.remove",
     "path": "circles/{circleId}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "removePeople": {
     "description": "Remove a person from a circle.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "plusDomains.circles.removePeople",
     "path": "circles/{circleId}/people",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update a circle's description.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "plusDomains.circles.update",
     "path": "circles/{circleId}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.write",
      "https://www.googleapis.com/auth/plus.login"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "comments": {
   "methods": {
    "get": {
     "description": "Get a comment.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.comments.get",
     "path": "comments/{commentId}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.stream.read"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Create a new comment in reply to an activity.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "plusDomains.comments.insert",
     "path": "activities/{activityId}/comments",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.stream.write"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List all of the comments for an activity.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.comments.list",
     "path": "activities/{activityId}/comments",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.stream.read"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "media": {
   "methods": {
    "insert": {
     "description": "Add a new media item to an album. The current upload size limitations are 36MB for a photo and 1GB for a video. Uploads do not count against quota if photos are less than 2048 pixels on their longest side or videos are less than 15 minutes in length.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "plusDomains.media.insert",
     "path": "people/{userId}/media/{collection}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.media.upload"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "people": {
   "methods": {
    "get": {
     "description": "Get a person's profile.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.people.get",
     "path": "people/{userId}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me",
      "https://www.googleapis.com/auth/plus.profiles.read",
      "https://www.googleapis.com/auth/userinfo.email",
      "https://www.googleapis.com/auth/userinfo.profile"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List all of the people in the specified collection.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.people.list",
     "path": "people/{userId}/people/{collection}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.me"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "listByActivity": {
     "description": "List all of the people in the specified collection for a particular activity.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.people.listByActivity",
     "path": "activities/{activityId}/people/{collection}",
     "scopes": [
      "https://www.googleapis.com/auth/plus.login",
      "https://www.googleapis.com/auth/plus.stream.read"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "listByCircle": {
     "description": "List all of the people who are members of a circle.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "plusDomains.people.listByCircle",
     "path": "circles/{circleId}/people",
     "scopes": [
      "https://www.googleapis.com/auth/plus.circles.read",
      "https://www.googleapis.com/auth/plus.login"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20170828",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "plusDomains/v1/",
 "title": "Google+ Domains API",
 "version": "v1",
 "version_module": null
}