{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/cloud-platform.read-only": {
     "description": "View your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/ndev.cloudman": {
     "description": "View and manage your Google Cloud Platform management resources and deployment status information"
    },
    "https://www.googleapis.com/auth/ndev.cloudman.readonly": {
     "description": "View your Google Cloud Platform management resources and deployment status information"
    },
    "https://www.googleapis.com/auth/replicapool": {
     "description": "View and manage replica pools"
    },
    "https://www.googleapis.com/auth/replicapool.readonly": {
     "description": "View replica pools"
    }
   }
  }
 },
 "basePath": "/replicapool/v1beta1/projects/",
 "baseUrl": "https://www.googleapis.com/replicapool/v1beta1/projects/",
 "batchPath": "batch/replicapool/v1beta1",
 "canonicalName": null,
 "description": "The Replica Pool API allows users to declaratively provision and manage groups of Google Compute Engine instances based on a common template.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/compute/docs/replica-pool/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/jlteK0NbZ8atlXF9lM-OU-ZamcA\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "replicapool:v1beta1",
 "kind": "discovery#restDescription",
 "labels": [
  "limited_availability"
 ],
 "methods": null,
 "name": "replicapool",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "pools": {
   "methods": {
    "delete": {
     "description": "Deletes a replica pool.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "replicapool.pools.delete",
     "path": "{projectName}/zones/{zone}/pools/{poolName}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/replicapool"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets information about a single replica pool.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "replicapool.pools.get",
     "path": "{projectName}/zones/{zone}/pools/{poolName}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/ndev.cloudman.readonly",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Inserts a new replica pool.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "replicapool.pools.insert",
     "path": "{projectName}/zones/{zone}/pools",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/replicapool"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List all replica pools.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "replicapool.pools.list",
     "path": "{projectName}/zones/{zone}/pools",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/ndev.cloudman.readonly",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "resize": {
     "description": "Resize a pool. This is an asynchronous operation, and multiple overlapping resize requests can be made. Replica Pools will use the information from the last resize request.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "replicapool.pools.resize",
     "path": "{projectName}/zones/{zone}/pools/{poolName}/resize",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/replicapool"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "updatetemplate": {
     "description": "Update the template used by the pool.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "replicapool.pools.updatetemplate",
     "path": "{projectName}/zones/{zone}/pools/{poolName}/updateTemplate",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/replicapool"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "replicas": {
   "methods": {
    "delete": {
     "description": "Deletes a replica from the pool.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "replicapool.replicas.delete",
     "path": "{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/replicapool"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets information about a specific replica.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "replicapool.replicas.get",
     "path": "{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/ndev.cloudman.readonly",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists all replicas in a pool.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "replicapool.replicas.list",
     "path": "{projectName}/zones/{zone}/pools/{poolName}/replicas",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/cloud-platform.read-only",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/ndev.cloudman.readonly",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "restart": {
     "description": "Restarts a replica in a pool.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "replicapool.replicas.restart",
     "path": "{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}/restart",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/ndev.cloudman",
      "https://www.googleapis.com/auth/replicapool"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20160512",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "replicapool/v1beta1/projects/",
 "title": "Replica Pool API",
 "version": "v1beta1",
 "version_module": null
}