{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/userinfo.email": {
     "description": "View your email address"
    },
    "https://www.google.com/calendar/feeds": {
     "description": "Manage your calendars"
    },
    "https://www.googleapis.com/auth/groups": {
     "description": "View and manage your Google Groups"
    },
    "https://www.googleapis.com/auth/forms.currentonly": {
     "description": "View and manage forms that this application has been installed in"
    },
    "https://www.googleapis.com/auth/drive": {
     "description": "View and manage the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/admin.directory.user": {
     "description": "View and manage the provisioning of users on your domain"
    },
    "https://www.googleapis.com/auth/admin.directory.group": {
     "description": "View and manage the provisioning of groups on your domain"
    },
    "https://www.googleapis.com/auth/spreadsheets": {
     "description": "View and manage your spreadsheets in Google Drive"
    },
    "https://mail.google.com/": {
     "description": "Read, send, delete, and manage your email"
    },
    "https://www.googleapis.com/auth/forms": {
     "description": "View and manage your forms in Google Drive"
    },
    "https://www.google.com/m8/feeds": {
     "description": "Manage your contacts"
    }
   }
  }
 },
 "basePath": "",
 "baseUrl": "https://script.googleapis.com/",
 "batchPath": "batch",
 "canonicalName": null,
 "description": "An API for managing and executing Google Apps Script projects.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/apps-script/execution/rest/v1/scripts/run",
 "etag": null,
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "script:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "script",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "scripts": {
   "methods": {
    "run": {
     "description": "Runs a function in an Apps Script project. The project must be deployed\nfor use with the Apps Script Execution API.\n\nThis method requires authorization with an OAuth 2.0 token that includes at\nleast one of the scopes listed in the [Authorization](#authorization)\nsection; script projects that do not require authorization cannot be\nexecuted through this API. To find the correct scopes to include in the\nauthentication token, open the project in the script editor, then se[...]",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "script.scripts.run",
     "path": "v1/scripts/{scriptId}:run",
     "scopes": [
      "https://mail.google.com/",
      "https://www.google.com/calendar/feeds",
      "https://www.google.com/m8/feeds",
      "https://www.googleapis.com/auth/admin.directory.group",
      "https://www.googleapis.com/auth/admin.directory.user",
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/forms",
      "https://www.googleapis.com/auth/forms.currentonly",
      "https://www.googleapis.com/auth/groups",
      "https://www.googleapis.com/auth/spreadsheets",
      "https://www.googleapis.com/auth/userinfo.email"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20170927",
 "rootUrl": "https://script.googleapis.com/",
 "servicePath": "",
 "title": "Google Apps Script Execution API",
 "version": "v1",
 "version_module": null
}