{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/drive.file": {
     "description": "View and manage Google Drive files and folders that you have opened or created with this app"
    },
    "https://www.googleapis.com/auth/spreadsheets.readonly": {
     "description": "View your Google Spreadsheets"
    },
    "https://www.googleapis.com/auth/drive.readonly": {
     "description": "View the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive": {
     "description": "View and manage the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/spreadsheets": {
     "description": "View and manage your spreadsheets in Google Drive"
    }
   }
  }
 },
 "basePath": "",
 "baseUrl": "https://sheets.googleapis.com/",
 "batchPath": "batch",
 "canonicalName": "Sheets",
 "description": "Reads and writes Google Sheets.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/sheets/",
 "etag": null,
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "sheets:v4",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "sheets",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "spreadsheets": {
   "methods": {
    "batchUpdate": {
     "description": "Applies one or more updates to the spreadsheet.\n\nEach request is validated before\nbeing applied. If any request is not valid then the entire request will\nfail and nothing will be applied.\n\nSome requests have replies to\ngive you some information about how\nthey are applied. The replies will mirror the requests.  For example,\nif you applied 4 updates and the 3rd one had a reply, then the\nresponse will have 2 empty replies, the actual reply, and another empty\nreply, i[...]",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "sheets.spreadsheets.batchUpdate",
     "path": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/spreadsheets"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "create": {
     "description": "Creates a spreadsheet, returning the newly created spreadsheet.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "sheets.spreadsheets.create",
     "path": "v4/spreadsheets",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/spreadsheets"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getByDataFilter": {
     "description": "Returns the spreadsheet at the given ID.\nThe caller must specify the spreadsheet ID.\n\nThis method differs from GetSpreadsheet in that it allows selecting\nwhich subsets of spreadsheet data to return by specifying a\ndataFilters parameter.\nMultiple DataFilters can be specified.  Specifying one or\nmore data filters will return the portions of the spreadsheet that\nintersect ranges matched by any of the filters.\n\nBy default, data within grids will not be returned.\nYou c[...]",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "sheets.spreadsheets.getByDataFilter",
     "path": "v4/spreadsheets/{spreadsheetId}:getByDataFilter",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/spreadsheets"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns the spreadsheet at the given ID.\nThe caller must specify the spreadsheet ID.\n\nBy default, data within grids will not be returned.\nYou can include grid data one of two ways:\n\n* Specify a field mask listing your desired fields using the `fields` URL\nparameter in HTTP\n\n* Set the includeGridData\nURL parameter to true.  If a field mask is set, the `includeGridData`\nparameter is ignored\n\nFor large spreadsheets, it is recommended to retrieve only the specific\n[...]",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "sheets.spreadsheets.get",
     "path": "v4/spreadsheets/{spreadsheetId}",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/spreadsheets",
      "https://www.googleapis.com/auth/spreadsheets.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "values": {
     "methods": {
      "batchClearByDataFilter": {
       "description": "Clears one or more ranges of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and one or more\nDataFilters. Ranges matching any of the specified data\nfilters will be cleared.  Only values are cleared -- all other properties\nof the cell (such as formatting, data validation, etc..) are kept.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.values.batchClearByDataFilter",
       "path": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "append": {
       "description": "Appends values to a spreadsheet. The input range is used to search for\nexisting data and find a \"table\" within that range. Values will be\nappended to the next row of the table, starting with the first column of\nthe table. See the\n[guide](/sheets/api/guides/values#appending_values)\nand\n[sample code](/sheets/api/samples/writing#append_values)\nfor specific details of how tables are detected and data is appended.\n\nThe caller must specify the spreadsheet ID, range, a[...]",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.values.append",
       "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "batchGetByDataFilter": {
       "description": "Returns one or more ranges of values that match the specified data filters.\nThe caller must specify the spreadsheet ID and one or more\nDataFilters.  Ranges that match any of the data filters in\nthe request will be returned.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.values.batchGetByDataFilter",
       "path": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "batchClear": {
       "description": "Clears one or more ranges of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and one or more ranges.\nOnly values are cleared -- all other properties of the cell (such as\nformatting, data validation, etc..) are kept.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.values.batchClear",
       "path": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns a range of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and a range.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "sheets.spreadsheets.values.get",
       "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/spreadsheets.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Sets values in a range of a spreadsheet.\nThe caller must specify the spreadsheet ID, range, and\na valueInputOption.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "sheets.spreadsheets.values.update",
       "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "batchUpdateByDataFilter": {
       "description": "Sets values in one or more ranges of a spreadsheet.\nThe caller must specify the spreadsheet ID,\na valueInputOption, and one or more\nDataFilterValueRanges.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.values.batchUpdateByDataFilter",
       "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "batchUpdate": {
       "description": "Sets values in one or more ranges of a spreadsheet.\nThe caller must specify the spreadsheet ID,\na valueInputOption, and one or more\nValueRanges.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.values.batchUpdate",
       "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "batchGet": {
       "description": "Returns one or more ranges of values from a spreadsheet.\nThe caller must specify the spreadsheet ID and one or more ranges.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "sheets.spreadsheets.values.batchGet",
       "path": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/spreadsheets.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "clear": {
       "description": "Clears values from a spreadsheet.\nThe caller must specify the spreadsheet ID and range.\nOnly values are cleared -- all other properties of the cell (such as\nformatting, data validation, etc..) are kept.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.values.clear",
       "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "sheets": {
     "methods": {
      "copyTo": {
       "description": "Copies a single sheet from a spreadsheet to another spreadsheet.\nReturns the properties of the newly created sheet.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.sheets.copyTo",
       "path": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    },
    "developerMetadata": {
     "methods": {
      "search": {
       "description": "Returns all developer metadata matching the specified DataFilter.\nIf the provided DataFilter represents a DeveloperMetadataLookup object,\nthis will return all DeveloperMetadata entries selected by it. If the\nDataFilter represents a location in a spreadsheet, this will return all\ndeveloper metadata associated with locations intersecting that region.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sheets.spreadsheets.developerMetadata.search",
       "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns the developer metadata with the specified ID.\nThe caller must specify the spreadsheet ID and the developer metadata's\nunique metadataId.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "sheets.spreadsheets.developerMetadata.get",
       "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/spreadsheets"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20170929",
 "rootUrl": "https://sheets.googleapis.com/",
 "servicePath": "",
 "title": "Google Sheets API",
 "version": "v4",
 "version_module": true
}