{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/siteverification": {
     "description": "Manage the list of sites and domains you control"
    },
    "https://www.googleapis.com/auth/siteverification.verify_only": {
     "description": "Manage your new site verifications with Google"
    }
   }
  }
 },
 "basePath": "/siteVerification/v1/",
 "baseUrl": "https://www.googleapis.com/siteVerification/v1/",
 "batchPath": "batch/siteVerification/v1",
 "canonicalName": null,
 "description": "Verifies ownership of websites or domains with Google.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/site-verification/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/91cCbhq1cUXIPKUTmb8zwBITGqo\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "siteVerification:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "siteVerification",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "webResource": {
   "methods": {
    "delete": {
     "description": "Relinquish ownership of a website or domain.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "siteVerification.webResource.delete",
     "path": "webResource/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Get the most current data for a website or domain.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "siteVerification.webResource.get",
     "path": "webResource/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getToken": {
     "description": "Get a verification token for placing on a website or domain.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "siteVerification.webResource.getToken",
     "path": "token",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification",
      "https://www.googleapis.com/auth/siteverification.verify_only"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Attempt verification of a website or domain.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "siteVerification.webResource.insert",
     "path": "webResource",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification",
      "https://www.googleapis.com/auth/siteverification.verify_only"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Get the list of your verified websites and domains.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "siteVerification.webResource.list",
     "path": "webResource",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Modify the list of owners for your website or domain. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "siteVerification.webResource.patch",
     "path": "webResource/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Modify the list of owners for your website or domain.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "siteVerification.webResource.update",
     "path": "webResource/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/siteverification"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20161114",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "siteVerification/v1/",
 "title": "Google Site Verification API",
 "version": "v1",
 "version_module": null
}