{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/spreadsheets.readonly": {
     "description": "View your Google Spreadsheets"
    },
    "https://www.googleapis.com/auth/drive": {
     "description": "View and manage the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.readonly": {
     "description": "View the files in your Google Drive"
    },
    "https://www.googleapis.com/auth/spreadsheets": {
     "description": "View and manage your spreadsheets in Google Drive"
    },
    "https://www.googleapis.com/auth/presentations": {
     "description": "View and manage your Google Slides presentations"
    },
    "https://www.googleapis.com/auth/presentations.readonly": {
     "description": "View your Google Slides presentations"
    }
   }
  }
 },
 "basePath": "",
 "baseUrl": "https://slides.googleapis.com/",
 "batchPath": "batch",
 "canonicalName": "Slides",
 "description": "An API for creating and editing Google Slides presentations.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/slides/",
 "etag": null,
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "slides:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "slides",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "presentations": {
   "methods": {
    "batchUpdate": {
     "description": "Applies one or more updates to the presentation.\n\nEach request is validated before\nbeing applied. If any request is not valid, then the entire request will\nfail and nothing will be applied.\n\nSome requests have replies to\ngive you some information about how they are applied. Other requests do\nnot need to return information; these each return an empty reply.\nThe order of replies matches that of the requests.\n\nFor example, suppose you call batchUpdate with four updat[...]",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "slides.presentations.batchUpdate",
     "path": "v1/presentations/{presentationId}:batchUpdate",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/presentations",
      "https://www.googleapis.com/auth/spreadsheets",
      "https://www.googleapis.com/auth/spreadsheets.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "create": {
     "description": "Creates a new presentation using the title given in the request. Other\nfields in the request are ignored.\nReturns the created presentation.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "slides.presentations.create",
     "path": "v1/presentations",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/presentations"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets the latest version of the specified presentation.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "slides.presentations.get",
     "path": "v1/presentations/{+presentationId}",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/presentations",
      "https://www.googleapis.com/auth/presentations.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "pages": {
     "methods": {
      "get": {
       "description": "Gets the latest version of the specified page in the presentation.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "slides.presentations.pages.get",
       "path": "v1/presentations/{presentationId}/pages/{pageObjectId}",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/presentations",
        "https://www.googleapis.com/auth/presentations.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "getThumbnail": {
       "description": "Generates a thumbnail of the latest version of the specified page in the\npresentation and returns a URL to the thumbnail image.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "slides.presentations.pages.getThumbnail",
       "path": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
       "scopes": [
        "https://www.googleapis.com/auth/drive",
        "https://www.googleapis.com/auth/drive.readonly",
        "https://www.googleapis.com/auth/presentations",
        "https://www.googleapis.com/auth/presentations.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20171002",
 "rootUrl": "https://slides.googleapis.com/",
 "servicePath": "",
 "title": "Google Slides API",
 "version": "v1",
 "version_module": true
}