{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/source.full_control": {
     "description": "Manage your source code repositories"
    },
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/source.read_only": {
     "description": "View the contents of your source code repositories"
    },
    "https://www.googleapis.com/auth/source.read_write": {
     "description": "Manage the contents of your source code repositories"
    }
   }
  }
 },
 "basePath": "",
 "baseUrl": "https://sourcerepo.googleapis.com/",
 "batchPath": "batch",
 "canonicalName": "Cloud Source Repositories",
 "description": "Access source code repositories hosted by Google.",
 "discoveryVersion": "v1",
 "documentationLink": "https://cloud.google.com/source-repositories/docs/apis",
 "etag": null,
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "sourcerepo:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "sourcerepo",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "projects": {
   "methods": null,
   "resources": {
    "repos": {
     "methods": {
      "testIamPermissions": {
       "description": "Returns permissions that a caller has on the specified resource.\nIf the resource does not exist, this will return an empty set of\npermissions, not a NOT_FOUND error.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sourcerepo.projects.repos.testIamPermissions",
       "path": "v1/{+resource}:testIamPermissions",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/source.full_control",
        "https://www.googleapis.com/auth/source.read_only",
        "https://www.googleapis.com/auth/source.read_write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "delete": {
       "description": "Deletes a repo.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "sourcerepo.projects.repos.delete",
       "path": "v1/{+name}",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/source.full_control",
        "https://www.googleapis.com/auth/source.read_only",
        "https://www.googleapis.com/auth/source.read_write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Returns all repos belonging to a project. The sizes of the repos are\nnot set by ListRepos.  To get the size of a repo, use GetRepo.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "sourcerepo.projects.repos.list",
       "path": "v1/{+name}/repos",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/source.full_control",
        "https://www.googleapis.com/auth/source.read_only",
        "https://www.googleapis.com/auth/source.read_write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "setIamPolicy": {
       "description": "Sets the access control policy on the specified resource. Replaces any\nexisting policy.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sourcerepo.projects.repos.setIamPolicy",
       "path": "v1/{+resource}:setIamPolicy",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/source.full_control",
        "https://www.googleapis.com/auth/source.read_only",
        "https://www.googleapis.com/auth/source.read_write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "create": {
       "description": "Creates a repo in the given project with the given name.\n\nIf the named repository already exists, `CreateRepo` returns\n`ALREADY_EXISTS`.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "sourcerepo.projects.repos.create",
       "path": "v1/{+parent}/repos",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/source.full_control",
        "https://www.googleapis.com/auth/source.read_only",
        "https://www.googleapis.com/auth/source.read_write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "getIamPolicy": {
       "description": "Gets the access control policy for a resource.\nReturns an empty policy if the resource exists and does not have a policy\nset.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "sourcerepo.projects.repos.getIamPolicy",
       "path": "v1/{+resource}:getIamPolicy",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/source.full_control",
        "https://www.googleapis.com/auth/source.read_only",
        "https://www.googleapis.com/auth/source.read_write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Returns information about a repo.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "sourcerepo.projects.repos.get",
       "path": "v1/{+name}",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/source.full_control",
        "https://www.googleapis.com/auth/source.read_only",
        "https://www.googleapis.com/auth/source.read_write"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20170908",
 "rootUrl": "https://sourcerepo.googleapis.com/",
 "servicePath": "",
 "title": "Cloud Source Repositories API",
 "version": "v1",
 "version_module": true
}