{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/tagmanager.delete.containers": {
     "description": "Delete your Google Tag Manager containers"
    },
    "https://www.googleapis.com/auth/tagmanager.edit.containers": {
     "description": "Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing"
    },
    "https://www.googleapis.com/auth/tagmanager.edit.containerversions": {
     "description": "Manage your Google Tag Manager container versions"
    },
    "https://www.googleapis.com/auth/tagmanager.manage.accounts": {
     "description": "View and manage your Google Tag Manager accounts"
    },
    "https://www.googleapis.com/auth/tagmanager.manage.users": {
     "description": "Manage user permissions of your Google Tag Manager account and container"
    },
    "https://www.googleapis.com/auth/tagmanager.publish": {
     "description": "Publish your Google Tag Manager container versions"
    },
    "https://www.googleapis.com/auth/tagmanager.readonly": {
     "description": "View your Google Tag Manager container and its subcomponents"
    }
   }
  }
 },
 "basePath": "/tagmanager/v1/",
 "baseUrl": "https://www.googleapis.com/tagmanager/v1/",
 "batchPath": "batch/tagmanager/v1",
 "canonicalName": "Tag Manager",
 "description": "Accesses Tag Manager accounts and containers.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/tag-manager/api/v1/",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/rRpL0Yww6KCNEEWca1YtyKw9Y48\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "tagmanager:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "tagmanager",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "accounts": {
   "methods": {
    "get": {
     "description": "Gets a GTM Account.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "tagmanager.accounts.get",
     "path": "accounts/{accountId}",
     "scopes": [
      "https://www.googleapis.com/auth/tagmanager.edit.containers",
      "https://www.googleapis.com/auth/tagmanager.manage.accounts",
      "https://www.googleapis.com/auth/tagmanager.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists all GTM Accounts that a user has access to.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "tagmanager.accounts.list",
     "path": "accounts",
     "scopes": [
      "https://www.googleapis.com/auth/tagmanager.edit.containers",
      "https://www.googleapis.com/auth/tagmanager.manage.accounts",
      "https://www.googleapis.com/auth/tagmanager.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a GTM Account.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "tagmanager.accounts.update",
     "path": "accounts/{accountId}",
     "scopes": [
      "https://www.googleapis.com/auth/tagmanager.manage.accounts"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "containers": {
     "methods": {
      "create": {
       "description": "Creates a Container.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "tagmanager.accounts.containers.create",
       "path": "accounts/{accountId}/containers",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.edit.containers"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "delete": {
       "description": "Deletes a Container.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "tagmanager.accounts.containers.delete",
       "path": "accounts/{accountId}/containers/{containerId}",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.delete.containers"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets a Container.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "tagmanager.accounts.containers.get",
       "path": "accounts/{accountId}/containers/{containerId}",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.edit.containers",
        "https://www.googleapis.com/auth/tagmanager.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists all Containers that belongs to a GTM Account.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "tagmanager.accounts.containers.list",
       "path": "accounts/{accountId}/containers",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.edit.containers",
        "https://www.googleapis.com/auth/tagmanager.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates a Container.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "tagmanager.accounts.containers.update",
       "path": "accounts/{accountId}/containers/{containerId}",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.edit.containers"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": {
      "environments": {
       "methods": {
        "create": {
         "description": "Creates a GTM Environment.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.environments.create",
         "path": "accounts/{accountId}/containers/{containerId}/environments",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes a GTM Environment.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "tagmanager.accounts.containers.environments.delete",
         "path": "accounts/{accountId}/containers/{containerId}/environments/{environmentId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets a GTM Environment.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.environments.get",
         "path": "accounts/{accountId}/containers/{containerId}/environments/{environmentId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists all GTM Environments of a GTM Container.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.environments.list",
         "path": "accounts/{accountId}/containers/{containerId}/environments",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "patch": {
         "description": "Updates a GTM Environment. This method supports patch semantics.",
         "etagRequired": null,
         "httpMethod": "PATCH",
         "id": "tagmanager.accounts.containers.environments.patch",
         "path": "accounts/{accountId}/containers/{containerId}/environments/{environmentId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "update": {
         "description": "Updates a GTM Environment.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "tagmanager.accounts.containers.environments.update",
         "path": "accounts/{accountId}/containers/{containerId}/environments/{environmentId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "folders": {
       "methods": {
        "create": {
         "description": "Creates a GTM Folder.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.folders.create",
         "path": "accounts/{accountId}/containers/{containerId}/folders",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes a GTM Folder.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "tagmanager.accounts.containers.folders.delete",
         "path": "accounts/{accountId}/containers/{containerId}/folders/{folderId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets a GTM Folder.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.folders.get",
         "path": "accounts/{accountId}/containers/{containerId}/folders/{folderId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists all GTM Folders of a Container.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.folders.list",
         "path": "accounts/{accountId}/containers/{containerId}/folders",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "update": {
         "description": "Updates a GTM Folder.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "tagmanager.accounts.containers.folders.update",
         "path": "accounts/{accountId}/containers/{containerId}/folders/{folderId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": {
        "entities": {
         "methods": {
          "list": {
           "description": "List all entities in a GTM Folder.",
           "etagRequired": null,
           "httpMethod": "GET",
           "id": "tagmanager.accounts.containers.folders.entities.list",
           "path": "accounts/{accountId}/containers/{containerId}/folders/{folderId}/entities",
           "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.readonly"
           ],
           "supportsMediaDownload": null,
           "supportsMediaUpload": null,
           "supportsSubscription": null,
           "useMediaDownloadService": null,
           "ETag": null
          }
         },
         "resources": null,
         "ETag": null
        }
       },
       "ETag": null
      },
      "move_folders": {
       "methods": {
        "update": {
         "description": "Moves entities to a GTM Folder.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "tagmanager.accounts.containers.move_folders.update",
         "path": "accounts/{accountId}/containers/{containerId}/move_folders/{folderId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "reauthorize_environments": {
       "methods": {
        "update": {
         "description": "Re-generates the authorization code for a GTM Environment.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "tagmanager.accounts.containers.reauthorize_environments.update",
         "path": "accounts/{accountId}/containers/{containerId}/reauthorize_environments/{environmentId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.publish"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "tags": {
       "methods": {
        "create": {
         "description": "Creates a GTM Tag.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.tags.create",
         "path": "accounts/{accountId}/containers/{containerId}/tags",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes a GTM Tag.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "tagmanager.accounts.containers.tags.delete",
         "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets a GTM Tag.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.tags.get",
         "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists all GTM Tags of a Container.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.tags.list",
         "path": "accounts/{accountId}/containers/{containerId}/tags",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "update": {
         "description": "Updates a GTM Tag.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "tagmanager.accounts.containers.tags.update",
         "path": "accounts/{accountId}/containers/{containerId}/tags/{tagId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "triggers": {
       "methods": {
        "create": {
         "description": "Creates a GTM Trigger.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.triggers.create",
         "path": "accounts/{accountId}/containers/{containerId}/triggers",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes a GTM Trigger.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "tagmanager.accounts.containers.triggers.delete",
         "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets a GTM Trigger.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.triggers.get",
         "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists all GTM Triggers of a Container.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.triggers.list",
         "path": "accounts/{accountId}/containers/{containerId}/triggers",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "update": {
         "description": "Updates a GTM Trigger.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "tagmanager.accounts.containers.triggers.update",
         "path": "accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "variables": {
       "methods": {
        "create": {
         "description": "Creates a GTM Variable.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.variables.create",
         "path": "accounts/{accountId}/containers/{containerId}/variables",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes a GTM Variable.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "tagmanager.accounts.containers.variables.delete",
         "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets a GTM Variable.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.variables.get",
         "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists all GTM Variables of a Container.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.variables.list",
         "path": "accounts/{accountId}/containers/{containerId}/variables",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "update": {
         "description": "Updates a GTM Variable.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "tagmanager.accounts.containers.variables.update",
         "path": "accounts/{accountId}/containers/{containerId}/variables/{variableId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      },
      "versions": {
       "methods": {
        "create": {
         "description": "Creates a Container Version.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.versions.create",
         "path": "accounts/{accountId}/containers/{containerId}/versions",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "delete": {
         "description": "Deletes a Container Version.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "tagmanager.accounts.containers.versions.delete",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "get": {
         "description": "Gets a Container Version.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.versions.get",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists all Container Versions of a GTM Container.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "tagmanager.accounts.containers.versions.list",
         "path": "accounts/{accountId}/containers/{containerId}/versions",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
          "https://www.googleapis.com/auth/tagmanager.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "publish": {
         "description": "Publishes a Container Version.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.versions.publish",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.publish"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "restore": {
         "description": "Restores a Container Version. This will overwrite the container's current configuration (including its variables, triggers and tags). The operation will not have any effect on the version that is being served (i.e. the published version).",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.versions.restore",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containers"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "undelete": {
         "description": "Undeletes a Container Version.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "tagmanager.accounts.containers.versions.undelete",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "update": {
         "description": "Updates a Container Version.",
         "etagRequired": null,
         "httpMethod": "PUT",
         "id": "tagmanager.accounts.containers.versions.update",
         "path": "accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
         "scopes": [
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      }
     },
     "ETag": null
    },
    "permissions": {
     "methods": {
      "create": {
       "description": "Creates a user's Account & Container Permissions.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "tagmanager.accounts.permissions.create",
       "path": "accounts/{accountId}/permissions",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "delete": {
       "description": "Removes a user from the account, revoking access to it and all of its containers.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "tagmanager.accounts.permissions.delete",
       "path": "accounts/{accountId}/permissions/{permissionId}",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets a user's Account & Container Permissions.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "tagmanager.accounts.permissions.get",
       "path": "accounts/{accountId}/permissions/{permissionId}",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "List all users that have access to the account along with Account and Container Permissions granted to each of them.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "tagmanager.accounts.permissions.list",
       "path": "accounts/{accountId}/permissions",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates a user's Account & Container Permissions.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "tagmanager.accounts.permissions.update",
       "path": "accounts/{accountId}/permissions/{permissionId}",
       "scopes": [
        "https://www.googleapis.com/auth/tagmanager.manage.users"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20160310",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "tagmanager/v1/",
 "title": "Tag Manager API",
 "version": "v1",
 "version_module": null
}