{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/taskqueue": {
     "description": "Manage your Tasks and Taskqueues"
    },
    "https://www.googleapis.com/auth/taskqueue.consumer": {
     "description": "Consume Tasks from your Taskqueues"
    }
   }
  }
 },
 "basePath": "/taskqueue/v1beta1/projects/",
 "baseUrl": "https://www.googleapis.com/taskqueue/v1beta1/projects/",
 "batchPath": "batch/taskqueue/v1beta1",
 "canonicalName": null,
 "description": "Accesses a Google App Engine Pull Task Queue over REST.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/appengine/docs/python/taskqueue/rest",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/UNHEtVyVE-POJmRW0SrDcBQE6KY\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "taskqueue:v1beta1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "taskqueue",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "taskqueues": {
   "methods": {
    "get": {
     "description": "Get detailed information about a TaskQueue.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "taskqueue.taskqueues.get",
     "path": "{project}/taskqueues/{taskqueue}",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "tasks": {
   "methods": {
    "delete": {
     "description": "Delete a task from a TaskQueue.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "taskqueue.tasks.delete",
     "path": "{project}/taskqueues/{taskqueue}/tasks/{task}",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Get a particular task from a TaskQueue.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "taskqueue.tasks.get",
     "path": "{project}/taskqueues/{taskqueue}/tasks/{task}",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "lease": {
     "description": "Lease 1 or more tasks from a TaskQueue.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "taskqueue.tasks.lease",
     "path": "{project}/taskqueues/{taskqueue}/tasks/lease",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "List Tasks in a TaskQueue",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "taskqueue.tasks.list",
     "path": "{project}/taskqueues/{taskqueue}/tasks",
     "scopes": [
      "https://www.googleapis.com/auth/taskqueue",
      "https://www.googleapis.com/auth/taskqueue.consumer"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20160428",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "taskqueue/v1beta1/projects/",
 "title": "TaskQueue API",
 "version": "v1beta1",
 "version_module": null
}