{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/tasks": {
     "description": "Manage your tasks"
    },
    "https://www.googleapis.com/auth/tasks.readonly": {
     "description": "View your tasks"
    }
   }
  }
 },
 "basePath": "/tasks/v1/",
 "baseUrl": "https://www.googleapis.com/tasks/v1/",
 "batchPath": "batch/tasks/v1",
 "canonicalName": null,
 "description": "Lets you manage your tasks and task lists.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/google-apps/tasks/firstapp",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/NWN6zUXbR398dbL3sE_mMEw339M\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "tasks:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "tasks",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "tasklists": {
   "methods": {
    "delete": {
     "description": "Deletes the authenticated user's specified task list.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "tasks.tasklists.delete",
     "path": "users/@me/lists/{tasklist}",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns the authenticated user's specified task list.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "tasks.tasklists.get",
     "path": "users/@me/lists/{tasklist}",
     "scopes": [
      "https://www.googleapis.com/auth/tasks",
      "https://www.googleapis.com/auth/tasks.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a new task list and adds it to the authenticated user's task lists.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "tasks.tasklists.insert",
     "path": "users/@me/lists",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns all the authenticated user's task lists.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "tasks.tasklists.list",
     "path": "users/@me/lists",
     "scopes": [
      "https://www.googleapis.com/auth/tasks",
      "https://www.googleapis.com/auth/tasks.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates the authenticated user's specified task list. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "tasks.tasklists.patch",
     "path": "users/@me/lists/{tasklist}",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates the authenticated user's specified task list.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "tasks.tasklists.update",
     "path": "users/@me/lists/{tasklist}",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "tasks": {
   "methods": {
    "clear": {
     "description": "Clears all completed tasks from the specified task list. The affected tasks will be marked as 'hidden' and no longer be returned by default when retrieving all tasks for a task list.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "tasks.tasks.clear",
     "path": "lists/{tasklist}/clear",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Deletes the specified task from the task list.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "tasks.tasks.delete",
     "path": "lists/{tasklist}/tasks/{task}",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Returns the specified task.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "tasks.tasks.get",
     "path": "lists/{tasklist}/tasks/{task}",
     "scopes": [
      "https://www.googleapis.com/auth/tasks",
      "https://www.googleapis.com/auth/tasks.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a new task on the specified task list.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "tasks.tasks.insert",
     "path": "lists/{tasklist}/tasks",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns all tasks in the specified task list.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "tasks.tasks.list",
     "path": "lists/{tasklist}/tasks",
     "scopes": [
      "https://www.googleapis.com/auth/tasks",
      "https://www.googleapis.com/auth/tasks.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "move": {
     "description": "Moves the specified task to another position in the task list. This can include putting it as a child task under a new parent and/or move it to a different position among its sibling tasks.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "tasks.tasks.move",
     "path": "lists/{tasklist}/tasks/{task}/move",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "patch": {
     "description": "Updates the specified task. This method supports patch semantics.",
     "etagRequired": null,
     "httpMethod": "PATCH",
     "id": "tasks.tasks.patch",
     "path": "lists/{tasklist}/tasks/{task}",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates the specified task.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "tasks.tasks.update",
     "path": "lists/{tasklist}/tasks/{task}",
     "scopes": [
      "https://www.googleapis.com/auth/tasks"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20141121",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "tasks/v1/",
 "title": "Tasks API",
 "version": "v1",
 "version_module": null
}