{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/ediscovery.readonly": {
     "description": "View your eDiscovery data"
    },
    "https://www.googleapis.com/auth/ediscovery": {
     "description": "Manage your eDiscovery data"
    }
   }
  }
 },
 "basePath": "",
 "baseUrl": "https://vault.googleapis.com/",
 "batchPath": "batch",
 "canonicalName": "Vault",
 "description": "Archiving and eDiscovery for G Suite.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/vault",
 "etag": null,
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "vault:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "vault",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "matters": {
   "methods": {
    "create": {
     "description": "Creates a new matter with the given name and description. The initial state\nis open, and the owner is the method caller. Returns the created matter\nwith default view.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "vault.matters.create",
     "path": "v1/matters",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "removePermissions": {
     "description": "Removes an account as a matter collaborator.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "vault.matters.removePermissions",
     "path": "v1/matters/{matterId}:removePermissions",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "reopen": {
     "description": "Reopens the specified matter. Returns matter with updated state.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "vault.matters.reopen",
     "path": "v1/matters/{matterId}:reopen",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "undelete": {
     "description": "Undeletes the specified matter. Returns matter with updated state.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "vault.matters.undelete",
     "path": "v1/matters/{matterId}:undelete",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "close": {
     "description": "Closes the specified matter. Returns matter with updated state.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "vault.matters.close",
     "path": "v1/matters/{matterId}:close",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets the specified matter.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "vault.matters.get",
     "path": "v1/matters/{matterId}",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery",
      "https://www.googleapis.com/auth/ediscovery.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates the specified matter.\nThis updates only the name and description of the matter, identified by\nmatter id. Changes to any other fields are ignored.\nReturns the default view of the matter.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "vault.matters.update",
     "path": "v1/matters/{matterId}",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Deletes the specified matter. Returns matter with updated state.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "vault.matters.delete",
     "path": "v1/matters/{matterId}",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "addPermissions": {
     "description": "Adds an account as a matter collaborator.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "vault.matters.addPermissions",
     "path": "v1/matters/{matterId}:addPermissions",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists matters the user has access to.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "vault.matters.list",
     "path": "v1/matters",
     "scopes": [
      "https://www.googleapis.com/auth/ediscovery",
      "https://www.googleapis.com/auth/ediscovery.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "holds": {
     "methods": {
      "delete": {
       "description": "Removes a hold by ID. This will release any HeldAccounts on this Hold.",
       "etagRequired": null,
       "httpMethod": "DELETE",
       "id": "vault.matters.holds.delete",
       "path": "v1/matters/{matterId}/holds/{holdId}",
       "scopes": [
        "https://www.googleapis.com/auth/ediscovery"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists holds within a matter. An empty page token in ListHoldsResponse\ndenotes no more holds to list.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "vault.matters.holds.list",
       "path": "v1/matters/{matterId}/holds",
       "scopes": [
        "https://www.googleapis.com/auth/ediscovery",
        "https://www.googleapis.com/auth/ediscovery.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "get": {
       "description": "Gets a hold by ID.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "vault.matters.holds.get",
       "path": "v1/matters/{matterId}/holds/{holdId}",
       "scopes": [
        "https://www.googleapis.com/auth/ediscovery",
        "https://www.googleapis.com/auth/ediscovery.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "update": {
       "description": "Updates the OU and/or query parameters of a hold. You cannot add accounts\nto a hold that covers an OU, nor can you add OUs to a hold that covers\nindividual accounts. Accounts listed in the hold will be ignored.",
       "etagRequired": null,
       "httpMethod": "PUT",
       "id": "vault.matters.holds.update",
       "path": "v1/matters/{matterId}/holds/{holdId}",
       "scopes": [
        "https://www.googleapis.com/auth/ediscovery"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "create": {
       "description": "Creates a hold in the given matter.",
       "etagRequired": null,
       "httpMethod": "POST",
       "id": "vault.matters.holds.create",
       "path": "v1/matters/{matterId}/holds",
       "scopes": [
        "https://www.googleapis.com/auth/ediscovery"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": {
      "accounts": {
       "methods": {
        "delete": {
         "description": "Removes a HeldAccount from a hold. If this request leaves the hold with\nno held accounts, the hold will not apply to any accounts.",
         "etagRequired": null,
         "httpMethod": "DELETE",
         "id": "vault.matters.holds.accounts.delete",
         "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
         "scopes": [
          "https://www.googleapis.com/auth/ediscovery"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "list": {
         "description": "Lists HeldAccounts for a hold. This will only list individually specified\nheld accounts. If the hold is on an OU, then use\n<a href=\"https://developers.google.com/admin-sdk/\">Admin SDK</a>\nto enumerate its members.",
         "etagRequired": null,
         "httpMethod": "GET",
         "id": "vault.matters.holds.accounts.list",
         "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
         "scopes": [
          "https://www.googleapis.com/auth/ediscovery",
          "https://www.googleapis.com/auth/ediscovery.readonly"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        },
        "create": {
         "description": "Adds a HeldAccount to a hold. Accounts can only be added to a hold that\nhas no held_org_unit set. Attempting to add an account to an OU-based\nhold will result in an error.",
         "etagRequired": null,
         "httpMethod": "POST",
         "id": "vault.matters.holds.accounts.create",
         "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
         "scopes": [
          "https://www.googleapis.com/auth/ediscovery"
         ],
         "supportsMediaDownload": null,
         "supportsMediaUpload": null,
         "supportsSubscription": null,
         "useMediaDownloadService": null,
         "ETag": null
        }
       },
       "resources": null,
       "ETag": null
      }
     },
     "ETag": null
    }
   },
   "ETag": null
  }
 },
 "revision": "20170812",
 "rootUrl": "https://vault.googleapis.com/",
 "servicePath": "",
 "title": "Google Vault API",
 "version": "v1",
 "version_module": true
}