{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/youtube": {
     "description": "Manage your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.force-ssl": {
     "description": "Manage your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.readonly": {
     "description": "View your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.upload": {
     "description": "Manage your YouTube videos"
    },
    "https://www.googleapis.com/auth/youtubepartner": {
     "description": "View and manage your assets and associated content on YouTube"
    },
    "https://www.googleapis.com/auth/youtubepartner-channel-audit": {
     "description": "View private information of your YouTube channel relevant during the audit process with a YouTube partner"
    }
   }
  }
 },
 "basePath": "/youtube/v3/",
 "baseUrl": "https://www.googleapis.com/youtube/v3/",
 "batchPath": "batch/youtube/v3",
 "canonicalName": "YouTube",
 "description": "Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/youtube/v3",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/BJDboFk3u5Gn0XCcgzl-Emxo56M\"",
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "youtube:v3",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "youtube",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "activities": {
   "methods": {
    "insert": {
     "description": "Posts a bulletin for a specific channel. (The user submitting the request must be authorized to act on the channel's behalf.)\n\nNote: Even though an activity resource can contain information about actions like a user rating a video or marking a video as a favorite, you need to use other API methods to generate those activity resources. For example, you would use the API's videos.rate() method to rate a video and the playlistItems.insert() method to mark a video as a favorit[...]",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.activities.insert",
     "path": "activities",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a list of channel activity events that match the request criteria. For example, you can retrieve events associated with a particular channel, events associated with the user's subscriptions and Google+ friends, or the YouTube home page feed, which is customized for each user.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.activities.list",
     "path": "activities",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "captions": {
   "methods": {
    "delete": {
     "description": "Deletes a specified caption track.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.captions.delete",
     "path": "captions",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "download": {
     "description": "Downloads a caption track. The caption track is returned in its original format unless the request specifies a value for the tfmt parameter and in its original language unless the request specifies a value for the tlang parameter.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.captions.download",
     "path": "captions/{id}",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": true,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Uploads a caption track.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.captions.insert",
     "path": "captions",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a list of caption tracks that are associated with a specified video. Note that the API response does not contain the actual captions and that the captions.download method provides the ability to retrieve a caption track.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.captions.list",
     "path": "captions",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a caption track. When updating a caption track, you can change the track's draft status, upload a new caption file for the track, or both.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.captions.update",
     "path": "captions",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "channelBanners": {
   "methods": {
    "insert": {
     "description": "Uploads a channel banner image to YouTube. This method represents the first two steps in a three-step process to update the banner image for a channel:\n\n- Call the channelBanners.insert method to upload the binary image data to YouTube. The image must have a 16:9 aspect ratio and be at least 2120x1192 pixels.\n- Extract the url property's value from the response that the API returns for step 1.\n- Call the channels.update method to update the channel's branding settings. S[...]",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.channelBanners.insert",
     "path": "channelBanners/insert",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.upload"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "channelSections": {
   "methods": {
    "delete": {
     "description": "Deletes a channelSection.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.channelSections.delete",
     "path": "channelSections",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Adds a channelSection for the authenticated user's channel.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.channelSections.insert",
     "path": "channelSections",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns channelSection resources that match the API request criteria.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.channelSections.list",
     "path": "channelSections",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Update a channelSection.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.channelSections.update",
     "path": "channelSections",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "channels": {
   "methods": {
    "list": {
     "description": "Returns a collection of zero or more channel resources that match the request criteria.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.channels.list",
     "path": "channels",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner",
      "https://www.googleapis.com/auth/youtubepartner-channel-audit"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a channel's metadata. Note that this method currently only supports updates to the channel resource's brandingSettings and invideoPromotion objects and their child properties.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.channels.update",
     "path": "channels",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "commentThreads": {
   "methods": {
    "insert": {
     "description": "Creates a new top-level comment. To add a reply to an existing comment, use the comments.insert method instead.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.commentThreads.insert",
     "path": "commentThreads",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a list of comment threads that match the API request parameters.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.commentThreads.list",
     "path": "commentThreads",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Modifies the top-level comment in a comment thread.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.commentThreads.update",
     "path": "commentThreads",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "comments": {
   "methods": {
    "delete": {
     "description": "Deletes a comment.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.comments.delete",
     "path": "comments",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a reply to an existing comment. Note: To create a top-level comment, use the commentThreads.insert method.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.comments.insert",
     "path": "comments",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a list of comments that match the API request parameters.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.comments.list",
     "path": "comments",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "markAsSpam": {
     "description": "Expresses the caller's opinion that one or more comments should be flagged as spam.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.comments.markAsSpam",
     "path": "comments/markAsSpam",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "setModerationStatus": {
     "description": "Sets the moderation status of one or more comments. The API request must be authorized by the owner of the channel or video associated with the comments.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.comments.setModerationStatus",
     "path": "comments/setModerationStatus",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Modifies a comment.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.comments.update",
     "path": "comments",
     "scopes": [
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "fanFundingEvents": {
   "methods": {
    "list": {
     "description": "Lists fan funding events for a channel.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.fanFundingEvents.list",
     "path": "fanFundingEvents",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "guideCategories": {
   "methods": {
    "list": {
     "description": "Returns a list of categories that can be associated with YouTube channels.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.guideCategories.list",
     "path": "guideCategories",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "i18nLanguages": {
   "methods": {
    "list": {
     "description": "Returns a list of application languages that the YouTube website supports.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.i18nLanguages.list",
     "path": "i18nLanguages",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "i18nRegions": {
   "methods": {
    "list": {
     "description": "Returns a list of content regions that the YouTube website supports.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.i18nRegions.list",
     "path": "i18nRegions",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "liveBroadcasts": {
   "methods": {
    "bind": {
     "description": "Binds a YouTube broadcast to a stream or removes an existing binding between a broadcast and a stream. A broadcast can only be bound to one video stream, though a video stream may be bound to more than one broadcast.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.liveBroadcasts.bind",
     "path": "liveBroadcasts/bind",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "control": {
     "description": "Controls the settings for a slate that can be displayed in the broadcast stream.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.liveBroadcasts.control",
     "path": "liveBroadcasts/control",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "delete": {
     "description": "Deletes a broadcast.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.liveBroadcasts.delete",
     "path": "liveBroadcasts",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a broadcast.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.liveBroadcasts.insert",
     "path": "liveBroadcasts",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a list of YouTube broadcasts that match the API request parameters.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.liveBroadcasts.list",
     "path": "liveBroadcasts",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "transition": {
     "description": "Changes the status of a YouTube live broadcast and initiates any processes associated with the new status. For example, when you transition a broadcast's status to testing, YouTube starts to transmit video to that broadcast's monitor stream. Before calling this method, you should confirm that the value of the status.streamStatus property for the stream bound to your broadcast is active.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.liveBroadcasts.transition",
     "path": "liveBroadcasts/transition",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a broadcast. For example, you could modify the broadcast settings defined in the liveBroadcast resource's contentDetails object.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.liveBroadcasts.update",
     "path": "liveBroadcasts",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "liveChatBans": {
   "methods": {
    "delete": {
     "description": "Removes a chat ban.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.liveChatBans.delete",
     "path": "liveChat/bans",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Adds a new ban to the chat.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.liveChatBans.insert",
     "path": "liveChat/bans",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "liveChatMessages": {
   "methods": {
    "delete": {
     "description": "Deletes a chat message.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.liveChatMessages.delete",
     "path": "liveChat/messages",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Adds a message to a live chat.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.liveChatMessages.insert",
     "path": "liveChat/messages",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists live chat messages for a specific chat.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.liveChatMessages.list",
     "path": "liveChat/messages",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "liveChatModerators": {
   "methods": {
    "delete": {
     "description": "Removes a chat moderator.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.liveChatModerators.delete",
     "path": "liveChat/moderators",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Adds a new moderator for the chat.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.liveChatModerators.insert",
     "path": "liveChat/moderators",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists moderators for a live chat.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.liveChatModerators.list",
     "path": "liveChat/moderators",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "liveStreams": {
   "methods": {
    "delete": {
     "description": "Deletes a video stream.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.liveStreams.delete",
     "path": "liveStreams",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a video stream. The stream enables you to send your video to YouTube, which can then broadcast the video to your audience.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.liveStreams.insert",
     "path": "liveStreams",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a list of video streams that match the API request parameters.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.liveStreams.list",
     "path": "liveStreams",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a video stream. If the properties that you want to change cannot be updated, then you need to create a new stream with the proper settings.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.liveStreams.update",
     "path": "liveStreams",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "playlistItems": {
   "methods": {
    "delete": {
     "description": "Deletes a playlist item.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.playlistItems.delete",
     "path": "playlistItems",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Adds a resource to a playlist.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.playlistItems.insert",
     "path": "playlistItems",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a collection of playlist items that match the API request parameters. You can retrieve all of the playlist items in a specified playlist or retrieve one or more playlist items by their unique IDs.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.playlistItems.list",
     "path": "playlistItems",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": true,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Modifies a playlist item. For example, you could update the item's position in the playlist.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.playlistItems.update",
     "path": "playlistItems",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "playlists": {
   "methods": {
    "delete": {
     "description": "Deletes a playlist.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.playlists.delete",
     "path": "playlists",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Creates a playlist.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.playlists.insert",
     "path": "playlists",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a collection of playlists that match the API request parameters. For example, you can retrieve all playlists that the authenticated user owns, or you can retrieve one or more playlists by their unique IDs.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.playlists.list",
     "path": "playlists",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Modifies a playlist. For example, you could change a playlist's title, description, or privacy status.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.playlists.update",
     "path": "playlists",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "search": {
   "methods": {
    "list": {
     "description": "Returns a collection of search results that match the query parameters specified in the API request. By default, a search result set identifies matching video, channel, and playlist resources, but you can also configure queries to only retrieve a specific type of resource.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.search.list",
     "path": "search",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "sponsors": {
   "methods": {
    "list": {
     "description": "Lists sponsors for a channel.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.sponsors.list",
     "path": "sponsors",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "subscriptions": {
   "methods": {
    "delete": {
     "description": "Deletes a subscription.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.subscriptions.delete",
     "path": "subscriptions",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Adds a subscription for the authenticated user's channel.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.subscriptions.insert",
     "path": "subscriptions",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns subscription resources that match the API request criteria.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.subscriptions.list",
     "path": "subscriptions",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "superChatEvents": {
   "methods": {
    "list": {
     "description": "Lists Super Chat events for a channel.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.superChatEvents.list",
     "path": "superChatEvents",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "thumbnails": {
   "methods": {
    "set": {
     "description": "Uploads a custom video thumbnail to YouTube and sets it for a video.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.thumbnails.set",
     "path": "thumbnails/set",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "videoAbuseReportReasons": {
   "methods": {
    "list": {
     "description": "Returns a list of abuse reasons that can be used for reporting abusive videos.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.videoAbuseReportReasons.list",
     "path": "videoAbuseReportReasons",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "videoCategories": {
   "methods": {
    "list": {
     "description": "Returns a list of categories that can be associated with YouTube videos.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.videoCategories.list",
     "path": "videoCategories",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "videos": {
   "methods": {
    "delete": {
     "description": "Deletes a YouTube video.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtube.videos.delete",
     "path": "videos",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "getRating": {
     "description": "Retrieves the ratings that the authorized user gave to a list of specified videos.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.videos.getRating",
     "path": "videos/getRating",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "insert": {
     "description": "Uploads a video to YouTube and optionally sets the video's metadata.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.videos.insert",
     "path": "videos",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Returns a list of videos that match the API request parameters.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtube.videos.list",
     "path": "videos",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "rate": {
     "description": "Add a like or dislike rating to a video or remove a rating from a video.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.videos.rate",
     "path": "videos/rate",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "reportAbuse": {
     "description": "Report abuse for a video.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.videos.reportAbuse",
     "path": "videos/reportAbuse",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "update": {
     "description": "Updates a video's metadata.",
     "etagRequired": null,
     "httpMethod": "PUT",
     "id": "youtube.videos.update",
     "path": "videos",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "watermarks": {
   "methods": {
    "set": {
     "description": "Uploads a watermark image to YouTube and sets it for a channel.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.watermarks.set",
     "path": "watermarks/set",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": true,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "unset": {
     "description": "Deletes a channel's watermark image.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtube.watermarks.unset",
     "path": "watermarks/unset",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/youtubepartner"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20171003",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "youtube/v3/",
 "title": "YouTube Data API",
 "version": "v3",
 "version_module": null
}