{
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/yt-analytics.readonly": {
     "description": "View YouTube Analytics reports for your YouTube content"
    },
    "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
     "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
    }
   }
  }
 },
 "basePath": "",
 "baseUrl": "https://youtubereporting.googleapis.com/",
 "batchPath": "batch",
 "canonicalName": "YouTube Reporting",
 "description": "Schedules reporting jobs containing your YouTube Analytics data and downloads the resulting bulk data reports in the form of CSV files.",
 "discoveryVersion": "v1",
 "documentationLink": "https://developers.google.com/youtube/reporting/v1/reports/",
 "etag": null,
 "exponentialBackoffDefault": null,
 "features": null,
 "id": "youtubereporting:v1",
 "kind": "discovery#restDescription",
 "labels": null,
 "methods": null,
 "name": "youtubereporting",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "packagePath": null,
 "protocol": "rest",
 "resources": {
  "media": {
   "methods": {
    "download": {
     "description": "Method for media download. Download is supported\non the URI `/v1/media/{+name}?alt=media`.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtubereporting.media.download",
     "path": "v1/media/{+resourceName}",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "supportsMediaDownload": true,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  },
  "jobs": {
   "methods": {
    "delete": {
     "description": "Deletes a job.",
     "etagRequired": null,
     "httpMethod": "DELETE",
     "id": "youtubereporting.jobs.delete",
     "path": "v1/jobs/{jobId}",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "get": {
     "description": "Gets a job.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtubereporting.jobs.get",
     "path": "v1/jobs/{jobId}",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "list": {
     "description": "Lists jobs.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtubereporting.jobs.list",
     "path": "v1/jobs",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    },
    "create": {
     "description": "Creates a job and returns it.",
     "etagRequired": null,
     "httpMethod": "POST",
     "id": "youtubereporting.jobs.create",
     "path": "v1/jobs",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": {
    "reports": {
     "methods": {
      "get": {
       "description": "Gets the metadata of a specific report.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "youtubereporting.jobs.reports.get",
       "path": "v1/jobs/{jobId}/reports/{reportId}",
       "scopes": [
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
        "https://www.googleapis.com/auth/yt-analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      },
      "list": {
       "description": "Lists reports created by a specific job.\nReturns NOT_FOUND if the job does not exist.",
       "etagRequired": null,
       "httpMethod": "GET",
       "id": "youtubereporting.jobs.reports.list",
       "path": "v1/jobs/{jobId}/reports",
       "scopes": [
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
        "https://www.googleapis.com/auth/yt-analytics.readonly"
       ],
       "supportsMediaDownload": null,
       "supportsMediaUpload": null,
       "supportsSubscription": null,
       "useMediaDownloadService": null,
       "ETag": null
      }
     },
     "resources": null,
     "ETag": null
    }
   },
   "ETag": null
  },
  "reportTypes": {
   "methods": {
    "list": {
     "description": "Lists report types.",
     "etagRequired": null,
     "httpMethod": "GET",
     "id": "youtubereporting.reportTypes.list",
     "path": "v1/reportTypes",
     "scopes": [
      "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
      "https://www.googleapis.com/auth/yt-analytics.readonly"
     ],
     "supportsMediaDownload": null,
     "supportsMediaUpload": null,
     "supportsSubscription": null,
     "useMediaDownloadService": null,
     "ETag": null
    }
   },
   "resources": null,
   "ETag": null
  }
 },
 "revision": "20171003",
 "rootUrl": "https://youtubereporting.googleapis.com/",
 "servicePath": "",
 "title": "YouTube Reporting API",
 "version": "v1",
 "version_module": null
}