// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-10-08
//     C# generater version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unoffical sample for the Directory directory_v1 API for C#. 
// This sample is designed to be used with the Google .Net client library. (https://github.com/google/google-api-dotnet-client)
// 
// API Description: The Admin SDK Directory API lets you view and manage enterprise resources such as users and groups, administrative notifications, security features, and more.
// API Documentation Link https://developers.google.com/admin-sdk/directory/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/Directory/directory_v1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// This sample code uses the Google .Net client library (https://github.com/google/google-api-dotnet-client)
//
// NuGet package:
//
// Location: https://www.nuget.org/packages/Google.Apis.Directory.directory_v1/ 
// Install Command: PM>  Install-Package Google.Apis.Directory.directory_v1
//
//------------------------------------------------------------------------------  
using Google.Apis.Directory.directory_v1;
using Google.Apis.Directory.directory_v1.Data;
using System;

namespace GoogleSamplecSharpSample.Directorydirectory_v1.Methods
{
  
    public static class AspsSample
    {


        /// <summary>
        /// Delete an ASP issued by a user. 
        /// Documentation https://developers.google.com/directory/directory_v1/reference/asps/delete
        /// Generation Note: This does not always build corectly.  Google needs to standardise things I need to figuer out which ones are wrong.
        /// </summary>
        /// <param name="service">Authenticated Directory service.</param>  
        /// <param name="userKey">Identifies the user in the API request. The value can be the user's primary email address, alias email address, or unique user ID.</param>
        /// <param name="codeId">The unique ID of the ASP to be deleted.</param>
        public static void Delete(DirectoryService service, string userKey, int? codeId)
        {
            try
            {
                // Initial validation.
                if (service == null)
                    throw new ArgumentNullException("service");
                if (userKey == null)
                    throw new ArgumentNullException(userKey);
                if (codeId == null)
                    throw new ArgumentNullException(codeId);

                // Make the request.
                 service.Asps.Delete(userKey, codeId).Execute();
            }
            catch (Exception ex)
            {
                throw new Exception("Request Asps.Delete failed.", ex);
            }
        }

        /// <summary>
        /// Get information about an ASP issued by a user. 
        /// Documentation https://developers.google.com/directory/directory_v1/reference/asps/get
        /// Generation Note: This does not always build corectly.  Google needs to standardise things I need to figuer out which ones are wrong.
        /// </summary>
        /// <param name="service">Authenticated Directory service.</param>  
        /// <param name="userKey">Identifies the user in the API request. The value can be the user's primary email address, alias email address, or unique user ID.</param>
        /// <param name="codeId">The unique ID of the ASP.</param>
        /// <returns>AspResponse</returns>
        public static Asp Get(DirectoryService service, string userKey, int? codeId)
        {
            try
            {
                // Initial validation.
                if (service == null)
                    throw new ArgumentNullException("service");
                if (userKey == null)
                    throw new ArgumentNullException(userKey);
                if (codeId == null)
                    throw new ArgumentNullException(codeId);

                // Make the request.
                return service.Asps.Get(userKey, codeId).Execute();
            }
            catch (Exception ex)
            {
                throw new Exception("Request Asps.Get failed.", ex);
            }
        }

        /// <summary>
        /// List the ASPs issued by a user. 
        /// Documentation https://developers.google.com/directory/directory_v1/reference/asps/list
        /// Generation Note: This does not always build corectly.  Google needs to standardise things I need to figuer out which ones are wrong.
        /// </summary>
        /// <param name="service">Authenticated Directory service.</param>  
        /// <param name="userKey">Identifies the user in the API request. The value can be the user's primary email address, alias email address, or unique user ID.</param>
        /// <returns>AspsResponse</returns>
        public static Asps List(DirectoryService service, string userKey)
        {
            try
            {
                // Initial validation.
                if (service == null)
                    throw new ArgumentNullException("service");
                if (userKey == null)
                    throw new ArgumentNullException(userKey);

                // Make the request.
                return service.Asps.List(userKey).Execute();
            }
            catch (Exception ex)
            {
                throw new Exception("Request Asps.List failed.", ex);
            }
        }
        
        }

        public static class SampleHelpers
        {

        /// <summary>
        /// Using reflection to apply optional parameters to the request.  
        /// 
        /// If the optonal parameters are null then we will just return the request as is.
        /// </summary>
        /// <param name="request">The request. </param>
        /// <param name="optional">The optional parameters. </param>
        /// <returns></returns>
        public static object ApplyOptionalParms(object request, object optional)
        {
            if (optional == null)
                return request;

            System.Reflection.PropertyInfo[] optionalProperties = (optional.GetType()).GetProperties();

            foreach (System.Reflection.PropertyInfo property in optionalProperties)
            {
                // Copy value from optional parms to the request.  They should have the same names and datatypes.
                System.Reflection.PropertyInfo piShared = (request.GetType()).GetProperty(property.Name);
				if (property.GetValue(optional, null) != null) // TODO Test that we do not add values for items that are null
					piShared.SetValue(request, property.GetValue(optional, null), null);
            }

            return request;
        }
    }
}